// GENERATED by scripts/build-resume-corpus.mjs — do not edit by hand.
import type { ResumeCorpus } from './resume-corpus';

export const RESUME_CORPUS: ResumeCorpus = {
  "header": {
    "name": "Jeremy Capps",
    "contacts": [
      "jeremy@nycwork.space",
      "linkedin.com/in/jeremycapps",
      "New York, NY"
    ]
  },
  "engagements": [
    {
      "id": "aroko_operations_source_of_truth",
      "organization": "Aroko",
      "roleContext": [
        "Head of Operations"
      ],
      "timePeriod": "2024–Present",
      "themes": [
        "internal_product",
        "project_operations",
        "notion_systems",
        "timesheet_design",
        "project_budgeting",
        "budget_consumption",
        "remaining_capacity",
        "project_estimation",
        "historical_estimation",
        "operations_systems",
        "source_of_truth",
        "financial_operations",
        "data_reconciliation"
      ],
      "roleFit": {
        "strongest": [
          "Technical Operations Manager",
          "Product Operations",
          "Operations Systems",
          "Implementation Operations",
          "Customer Success Systems"
        ],
        "secondary": [
          "Fintech Operations",
          "AI Workflow Governance"
        ]
      },
      "caution": [
        "Frame as an internal project-operations system or budgeting and estimating workflow, not as a full ERP or standalone software platform."
      ],
      "bullets": [
        {
          "id": "aroko_operations_source_of_truth.b1",
          "text": "Built a Notion-based project budgeting and estimating system that connected timesheets to an existing projects board and calculated budget consumption from hours worked.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#aroko_operations_source_of_truth"
          ]
        },
        {
          "id": "aroko_operations_source_of_truth.b2",
          "text": "Wrote queries and rollups to surface remaining project budget or capacity and used historical delivery data to improve future estimates.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#aroko_operations_source_of_truth"
          ]
        },
        {
          "id": "aroko_operations_source_of_truth.b3",
          "text": "Extended the workflow into broader operational reconciliation across YNAB, Bill.com, Notion, and spreadsheets, clarifying payments, hours, work categories, and source reliability.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#aroko_operations_source_of_truth"
          ]
        }
      ]
    },
    {
      "id": "aroko_web_migration_technical_direction",
      "organization": "Aroko",
      "roleContext": [
        "Head of Operations",
        "Lead Web Designer",
        "Technical Director for client web work"
      ],
      "timePeriod": "2024–Present",
      "themes": [
        "technical_documentation",
        "scope_of_work",
        "website_migration",
        "client_implementation",
        "seo_handoff",
        "content_operations",
        "stakeholder_coordination",
        "launch_readiness",
        "delivery_qa"
      ],
      "roleFit": {
        "strongest": [
          "Technical Operations Manager",
          "Product Operations",
          "Implementation Manager",
          "Solutions Consultant",
          "Customer Success Architect",
          "Digital Product Operations"
        ],
        "secondary": [
          "Technical Program Manager",
          "Web Producer",
          "Technical Writer"
        ]
      },
      "caution": [],
      "bullets": [
        {
          "id": "aroko_web_migration_technical_direction.b1",
          "text": "Led technical web delivery for client projects, translating business, SEO, and content requirements into migration roadmaps, scopes of work, implementation plans, and QA checkpoints.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#aroko_web_migration_technical_direction"
          ]
        },
        {
          "id": "aroko_web_migration_technical_direction.b2",
          "text": "Partnered with clients, SEO teams, and content managers to plan website migrations across technical requirements, content workflows, stakeholder approvals, and delivery milestones.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#aroko_web_migration_technical_direction"
          ]
        },
        {
          "id": "aroko_web_migration_technical_direction.b3",
          "text": "Authored scopes of work, migration roadmaps, and technical handoff documentation clarifying requirements, dependencies, ownership, and launch-readiness criteria.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#aroko_web_migration_technical_direction"
          ]
        }
      ]
    },
    {
      "id": "aroko_junior_contributor_leadership",
      "organization": "Aroko",
      "roleContext": [
        "Head of Operations",
        "Lead Web Designer / Technical Director"
      ],
      "timePeriod": "2024–Present",
      "themes": [
        "lightweight_people_leadership",
        "project_leadership",
        "feedback_cycles",
        "task_scoping",
        "delivery_quality",
        "mentorship"
      ],
      "roleFit": {
        "strongest": [
          "Technical Operations Manager",
          "Product Operations",
          "Implementation Manager",
          "Program Operations"
        ],
        "secondary": [
          "Design Operations",
          "Web Delivery Lead"
        ]
      },
      "caution": [
        "Frame as project/contributor leadership, not formal people management unless more detail is added."
      ],
      "bullets": [
        {
          "id": "aroko_junior_contributor_leadership.b1",
          "text": "Led junior contributors through scoped web and operations projects, translating ambiguous requirements into clear tasks, feedback cycles, and deliverables.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#aroko_junior_contributor_leadership"
          ]
        },
        {
          "id": "aroko_junior_contributor_leadership.b2",
          "text": "Reviewed and guided junior design/web work to ensure client needs, brand direction, technical requirements, and delivery standards were met.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#aroko_junior_contributor_leadership"
          ]
        },
        {
          "id": "aroko_junior_contributor_leadership.b3",
          "text": "Coordinated project execution across junior contributors, clients, and internal priorities while maintaining timeline and quality expectations.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#aroko_junior_contributor_leadership"
          ]
        }
      ]
    },
    {
      "id": "zocdoc_design_system_migrations",
      "organization": "Zocdoc",
      "roleContext": [
        "Design Systems Engineer",
        "Frontend Software Engineer"
      ],
      "timePeriod": "2021–2024",
      "themes": [
        "design_systems",
        "product_engineering",
        "accessibility",
        "migration",
        "cross_functional_delivery",
        "implementation_documentation",
        "adoption",
        "frontend_architecture",
        "typescript",
        "react"
      ],
      "roleFit": {
        "strongest": [
          "Product Engineer",
          "Technical Product Operations",
          "Design Systems Engineer",
          "Frontend Engineer",
          "Digital Product Operations"
        ],
        "secondary": [
          "Implementation / Migration Lead",
          "Accessibility Program Operations"
        ]
      },
      "caution": [],
      "bullets": [
        {
          "id": "zocdoc_design_system_migrations.b1",
          "text": "Owned a portfolio of shared TypeScript/React design-system components and supported their migration across production healthcare surfaces under Zocdoc's accessibility program.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#zocdoc_design_system_migrations"
          ]
        },
        {
          "id": "zocdoc_design_system_migrations.b2",
          "text": "Participated in an accessibility audit across production pages and components, then contributed component reconciliation and migration work toward the team's WCAG-compliance objective.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#zocdoc_design_system_migrations"
          ]
        },
        {
          "id": "zocdoc_design_system_migrations.b3",
          "text": "Built and documented assigned components, supported engineering-team migration and QA, and implemented a gradual A/B-tested Header rollout using Zocdoc's existing experimentation infrastructure.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#zocdoc_design_system_migrations"
          ]
        }
      ]
    },
    {
      "id": "zocdoc_delivery_workflows_and_documentation",
      "organization": "Zocdoc",
      "roleContext": [
        "Design Systems Engineer"
      ],
      "timePeriod": "2022–2024",
      "themes": [
        "technical_operations",
        "engineering_operations",
        "documentation",
        "delivery_process",
        "handoff",
        "workflow_improvement"
      ],
      "roleFit": {
        "strongest": [
          "Technical Operations Manager",
          "Product Operations",
          "Engineering Operations",
          "Technical Program Management"
        ],
        "secondary": [
          "Product Engineer",
          "Design Systems Operations"
        ]
      },
      "caution": [],
      "bullets": [
        {
          "id": "zocdoc_delivery_workflows_and_documentation.b1",
          "text": "Built Jira dashboards, implementation notes, and handoff materials that improved team planning and made design system work easier to maintain across teams.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#zocdoc_delivery_workflows_and_documentation"
          ]
        },
        {
          "id": "zocdoc_delivery_workflows_and_documentation.b2",
          "text": "Implemented a PR merge template that streamlined multi-developer workflows and reduced average merge time by a full workday.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#zocdoc_delivery_workflows_and_documentation"
          ]
        },
        {
          "id": "zocdoc_delivery_workflows_and_documentation.b3",
          "text": "Broke larger technical initiatives into smaller tickets and planning workflows, increasing developer velocity by 2–3 points per sprint.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#zocdoc_delivery_workflows_and_documentation"
          ]
        }
      ]
    },
    {
      "id": "applied_software_api_customer_workflows",
      "organization": "Applied Software",
      "roleContext": [
        "Software / Product Engineer",
        "C# Software Engineer"
      ],
      "timePeriod": "2019–2021",
      "themes": [
        "product_ownership",
        "end_to_end_integration_delivery",
        "construction_data_integration",
        "api_integrations",
        "authentication",
        "customer_workflows",
        "technical_support_enablement",
        "roadmap_collaboration",
        "construction_software",
        "implementation"
      ],
      "roleFit": {
        "strongest": [
          "Technical Consultant",
          "Implementation Engineer",
          "Product Operations",
          "API Product / Developer Tools",
          "Customer Success Architect"
        ],
        "secondary": [
          "Software Engineer",
          "Solutions Engineer"
        ]
      },
      "caution": [],
      "bullets": [
        {
          "id": "applied_software_api_customer_workflows.b1",
          "text": "Developed 360Sync integrations for Procore, Bluebeam, Asite, and Viewpoint from initial design through completion, using the inherited BIM 360 integration as the architectural blueprint.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#applied_software_api_customer_workflows"
          ]
        },
        {
          "id": "applied_software_api_customer_workflows.b2",
          "text": "Owned end-to-end integration delivery across API research, authentication, data mapping, implementation, testing, release support, and customer troubleshooting for construction software workflows.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#applied_software_api_customer_workflows"
          ]
        },
        {
          "id": "applied_software_api_customer_workflows.b3",
          "text": "Authored 5+ REST API wrapper libraries consumed by internal and customer-facing projects, standardizing integration patterns across technical workflows.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#applied_software_api_customer_workflows"
          ]
        },
        {
          "id": "applied_software_api_customer_workflows.b4",
          "text": "Introduced trace logging to key workflows, reducing customer support troubleshooting time by an average of 3–4 business days.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#applied_software_api_customer_workflows"
          ]
        },
        {
          "id": "applied_software_api_customer_workflows.b5",
          "text": "Worked with technical customers and internal stakeholders to translate workflow needs, integration requirements, and support pain points into implementation-ready software.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#applied_software_api_customer_workflows"
          ]
        }
      ]
    },
    {
      "id": "genesco_legacy_modernization",
      "organization": "Genesco",
      "roleContext": [
        "Software Engineer / Legacy Modernization Contributor"
      ],
      "timePeriod": "2017–2019",
      "themes": [
        "legacy_modernization",
        "business_logic_translation",
        "java",
        "operational_continuity",
        "technical_documentation",
        "constrained_systems"
      ],
      "roleFit": {
        "strongest": [
          "Technical Operations",
          "Implementation",
          "Product Engineer",
          "Enterprise Systems"
        ],
        "secondary": [
          "Technical Program Management"
        ]
      },
      "caution": [],
      "bullets": [
        {
          "id": "genesco_legacy_modernization.b1",
          "text": "Contributed to modernization work involving legacy COBOL systems and Java-based replacement workflows, translating embedded business logic into maintainable implementation.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#genesco_legacy_modernization"
          ]
        },
        {
          "id": "genesco_legacy_modernization.b2",
          "text": "Worked with legacy data flows, production constraints, and cross-functional stakeholders to support incremental migration without disrupting operational continuity.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#genesco_legacy_modernization"
          ]
        }
      ]
    },
    {
      "id": "domain_corus_agentic_context_infrastructure",
      "organization": "Independent / Domain",
      "roleContext": [
        "AI-assisted context coordination prototype",
        "Product / architecture project"
      ],
      "timePeriod": "2024–Present",
      "themes": [
        "ai_workflow_infrastructure",
        "agentic_systems",
        "context_management",
        "source_bound_claims",
        "auditability",
        "workflow_state",
        "approval_gates",
        "product_architecture"
      ],
      "roleFit": {
        "strongest": [
          "AI Product Operations",
          "Agentic Workflow Strategy",
          "Developer Tools Product",
          "Technical Product Strategy",
          "Product Systems Architect"
        ],
        "secondary": [
          "Technical Program Manager",
          "AI Platform Operations"
        ]
      },
      "caution": [
        "Frame as independent product/project unless incorporated or externally validated."
      ],
      "bullets": [
        {
          "id": "domain_corus_agentic_context_infrastructure.b1",
          "text": "Designed and prototyped AI-assisted workflow-state infrastructure for preserving context across sources, tasks, claims, evidence, handoffs, decisions, and recovery checkpoints.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#domain_corus_agentic_context_infrastructure"
          ]
        },
        {
          "id": "domain_corus_agentic_context_infrastructure.b2",
          "text": "Built product concepts for recoverable AI workspaces using source manifests, evidence-bound claims, admitted/rejected states, verification commands, audit logs, and approval-gated execution.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#domain_corus_agentic_context_infrastructure"
          ]
        },
        {
          "id": "domain_corus_agentic_context_infrastructure.b3",
          "text": "Created reusable protocol structures for agent workflows, including operating principles, execution steps, constraints, success criteria, validation rules, and handoff formats.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#domain_corus_agentic_context_infrastructure"
          ]
        }
      ]
    },
    {
      "id": "weill_cornell_data_pipeline",
      "organization": "Weill Cornell Medicine",
      "roleContext": [
        "Freelance Developer"
      ],
      "timePeriod": "2020–2021",
      "themes": [
        "data_pipeline",
        "spreadsheet_automation",
        "workflow_automation",
        "admissions_data",
        "data_cleaning"
      ],
      "roleFit": {
        "strongest": [
          "Technical Operations",
          "Data Operations",
          "Process Automation",
          "Product Operations"
        ],
        "secondary": [
          "Software Engineer"
        ]
      },
      "caution": [],
      "bullets": [
        {
          "id": "weill_cornell_data_pipeline.b1",
          "text": "Developed a Python-to-Google-Sheets integration to parse, clean, and update admissions data for Weill Cornell Medicine.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#weill_cornell_data_pipeline"
          ]
        }
      ]
    },
    {
      "id": "freelance_design_program_management",
      "organization": "Independent / Freelance",
      "roleContext": [
        "Freelance Designer & Program Manager"
      ],
      "timePeriod": "2020–2025",
      "themes": [
        "program_management",
        "web_design",
        "product_design",
        "agency_operations",
        "quoting_systems",
        "design_systems",
        "workflow_optimization"
      ],
      "roleFit": {
        "strongest": [
          "Product Operations",
          "Digital Delivery Operations",
          "Design Operations",
          "Web / Creative Operations"
        ],
        "secondary": [
          "Technical Operations",
          "Business Operations"
        ]
      },
      "caution": [],
      "bullets": [
        {
          "id": "freelance_design_program_management.b1",
          "text": "Developed a 90-day program roadmap for a design agency to optimize workflows and initiate its internal Figma design system.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#freelance_design_program_management"
          ]
        },
        {
          "id": "freelance_design_program_management.b2",
          "text": "Implemented a Composable Costing methodology that standardized project quoting and improved client transparency.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#freelance_design_program_management"
          ]
        },
        {
          "id": "freelance_design_program_management.b3",
          "text": "Oversaw product design of a Shutterstock landing page, emphasizing key business insights to drive user engagement.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#freelance_design_program_management"
          ]
        }
      ]
    },
    {
      "id": "new_inc_cultural_systems_research",
      "organization": "NEW INC / New Museum",
      "roleContext": [
        "Musician and researcher",
        "Creative systems / cultural systems researcher",
        "Interview-based editorial contributor"
      ],
      "timePeriod": "2025–2026",
      "themes": [
        "new_inc",
        "creative_systems",
        "cultural_systems_research",
        "interview_research",
        "editorial_framing",
        "pattern_language",
        "how_music_works",
        "emerging_technology_context",
        "high_context_expert_workflows",
        "translation_between_creative_and_systems_language"
      ],
      "roleFit": {
        "strongest": [
          "AI Product Strategy",
          "AI Workflow Product / Internal AI Tools",
          "Technical Product Operations",
          "Consulting AI Workflow Translation",
          "Emerging Technology Strategy",
          "Creative Technology / Cultural Systems"
        ],
        "secondary": [
          "Product Manager, AI Foundry",
          "Strategy / Innovation Operations",
          "Editorial Research / Cultural Strategy"
        ]
      },
      "caution": [],
      "bullets": [
        {
          "id": "new_inc_cultural_systems_research.b1",
          "text": "Conducted interview-based cultural systems research through NEW INC, connecting David Byrne's How Music Works with Christopher Alexander's pattern-language thinking to examine how context, space, and systems shape creative work.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#new_inc_cultural_systems_research"
          ]
        },
        {
          "id": "new_inc_cultural_systems_research.b2",
          "text": "Produced high-context editorial research across music, cultural infrastructure, and creative systems, translating abstract systems thinking into publishable interview framing.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#new_inc_cultural_systems_research"
          ]
        },
        {
          "id": "new_inc_cultural_systems_research.b3",
          "text": "Developed a cultural-systems lens on emerging technology adoption: how tools become usable workflows, spaces, and practices for expert communities.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#new_inc_cultural_systems_research"
          ]
        }
      ]
    },
    {
      "id": "new_inc_big_shot_music_curation",
      "organization": "NEW INC / New Museum / Water Street Armory",
      "roleContext": [
        "Music curator",
        "Cultural programming contributor",
        "Playlist researcher for Big Shot talk series"
      ],
      "timePeriod": "2025–2026",
      "themes": [
        "new_inc",
        "new_museum",
        "water_street_armory",
        "big_shot",
        "music_curation",
        "playlist_research",
        "cultural_programming",
        "audience_experience_design",
        "executive_context_research",
        "artist_author_context_research",
        "high_context_creative_workflows",
        "public_programming",
        "community_and_cultural_infrastructure"
      ],
      "roleFit": {
        "strongest": [
          "Cultural Strategy",
          "Creative Technology / Cultural Systems",
          "Community Programming",
          "Editorial Research / Cultural Research",
          "Brand / Experience Strategy",
          "AI Workflow Product for Expert Creative Teams"
        ],
        "secondary": [
          "Product Strategy",
          "Content Operations",
          "Event Programming Operations",
          "Partnerships / Cultural Operations"
        ]
      },
      "caution": [],
      "bullets": [
        {
          "id": "new_inc_big_shot_music_curation.b1",
          "text": "Curated music and playlist research for Big Shot, a New Museum / Water Street Armory talk series, tailoring guest-specific listening contexts for artists, authors, executives, and cultural audiences.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#new_inc_big_shot_music_curation"
          ]
        },
        {
          "id": "new_inc_big_shot_music_curation.b2",
          "text": "Created custom playlist concepts for speakers including Gabe Whaley of MSCHF, author Radha Lin Chaddah, and Craig Kallman, connecting biographical, cultural, and industry context into audience-facing music programming.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#new_inc_big_shot_music_curation"
          ]
        },
        {
          "id": "new_inc_big_shot_music_curation.b3",
          "text": "Supported cultural programming through high-context research, music curation, attendee-facing playlist assets, and follow-up materials for the Big Shot speaker series.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#new_inc_big_shot_music_curation"
          ]
        }
      ]
    },
    {
      "id": "tempo_strategy_framework_model",
      "organization": "Independent / Tempo",
      "roleContext": [
        "Product and knowledge-modeling prototype",
        "Strategy-framework systems experiment"
      ],
      "timePeriod": "2026",
      "themes": [
        "strategy_framework_modeling",
        "knowledge_architecture",
        "consulting_ip_productization",
        "source_provenance",
        "framework_applicability",
        "protocol_design",
        "validation_architecture",
        "organizational_profiles",
        "ai_product_experimentation",
        "product_tradeoff_analysis",
        "obsidian_knowledge_systems",
        "computational_strategy"
      ],
      "roleFit": {
        "strongest": [
          "Senior Product Manager, AI Foundry",
          "AI Product Strategy",
          "Internal AI Platform Product",
          "Consulting Knowledge Systems",
          "Product Systems Architect"
        ],
        "secondary": [
          "Knowledge Management Product",
          "Strategy and Innovation Operations",
          "Technical Product Management"
        ]
      },
      "caution": [
        "Describe Tempo as an exploratory prototype, not a deployed multi-agent platform.",
        "Do not present heuristic weights or derived organizational scores as validated business measures.",
        "Do not imply knowledge of MAIA's internal architecture; frame the connection as the same class of product problem."
      ],
      "bullets": [
        {
          "id": "tempo_strategy_framework_model.b1",
          "text": "Built an Obsidian-based strategy-modeling prototype that represented consulting frameworks as structured logic sources linked to organizational profiles, application protocols, and validators.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_strategy_framework_model"
          ]
        },
        {
          "id": "tempo_strategy_framework_model.b2",
          "text": "Modeled framework applicability through source provenance, triggers, interrogation questions, authority boundaries, and validation references rather than relying on a single generation prompt.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_strategy_framework_model"
          ]
        },
        {
          "id": "tempo_strategy_framework_model.b3",
          "text": "Tested layered and weighted approaches to multi-framework organizational analysis, then used the architectural limitations to inform the later Domain and Corus product models.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_strategy_framework_model"
          ]
        }
      ]
    },
    {
      "id": "jeremy_domain_ai_multi_provider_llm_orchestration",
      "organization": "Independent / Domain",
      "roleContext": [
        "Sole architect and implementer",
        "Independent AI infrastructure project",
        "Multi-provider LLM orchestration system"
      ],
      "timePeriod": "2026-07 – Present (verified activity July 2026)",
      "themes": [
        "llm_orchestration",
        "multi_provider_abstraction",
        "genai_infrastructure",
        "evidence_grounded_generation",
        "model_context_protocol",
        "token_budgeting",
        "data_egress_control",
        "evaluation_harness",
        "hallucination_prevention",
        "agentic_systems",
        "typescript_backend",
        "provenance_and_auditability",
        "approval_gates",
        "event_sourced_recovery"
      ],
      "roleFit": {
        "strongest": [
          "Forward Deployed Engineer",
          "AI Solutions Engineer",
          "GenAI Implementation Consultant",
          "AI Platform Engineer",
          "Technical Product Strategy (AI)",
          "Developer Tools Product"
        ],
        "secondary": [
          "Solutions Architect",
          "AI Product Operations",
          "Technical Program Manager (AI)"
        ]
      },
      "caution": [
        "This is Jeremy's own infrastructure in daily personal use — NOT a client engagement and NOT a commercial production deployment. Never describe it as shipped to a client, to customers, or to external users.",
        "Do not cite evaluation scores as achievements. The harness measures quality; the sampled fixture run scored low (requirement_coverage 0.029, capability_recall 0). The supported claim is that the measurement exists and is enforced, not that the system scores well.",
        "Live provider runs are a subset of the output corpus. Many of the 79 run directories are fixture or mock executions (provider: fixture, model: mock-claude-reducer). Do not imply every run was live.",
        "estimated_cost_usd is present in the metrics schema but was null in inspected records — cost tracking is modeled, not measured. Do not cite cost figures.",
        "Single-operator system with no external users, no uptime/SLA history, and no confirmed public GitHub remote (local git only, 31 commits). Do not imply scale, traffic, or team.",
        "Do not convert this into a claim of any working relationship with Anthropic, OpenAI, or Google. Jeremy is an API consumer of all three, nothing more.",
        "Model identifiers (claude-sonnet-5, gpt-5.5-pro-2026-04-23, gemini-3.1-flash-lite) are recorded as found in artifacts; re-verify before citing exact versions externally."
      ],
      "bullets": [
        {
          "id": "jeremy_domain_ai_multi_provider_llm_orchestration.b1",
          "text": "Built a multi-provider LLM orchestration system (~15,700 lines of TypeScript) executing live against Anthropic Claude Sonnet 5, OpenAI GPT-5.5 Pro, and Google Gemini 3.1 Flash Lite through a single provider-neutral execution boundary normalizing three distinct API surfaces.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_ai_multi_provider_llm_orchestration"
          ]
        },
        {
          "id": "jeremy_domain_ai_multi_provider_llm_orchestration.b2",
          "text": "Designed guardrails for production-shaped LLM execution: token-budget directives that withhold calls rather than exceed budget, per-payload data-egress classification (synthetic/public/private/restricted), bounded retry with failure classification, and provider rerouting.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_ai_multi_provider_llm_orchestration"
          ]
        },
        {
          "id": "jeremy_domain_ai_multi_provider_llm_orchestration.b3",
          "text": "Implemented an evaluation harness scoring every generation run on evidence accuracy, requirement coverage, and unsupported claims against a golden baseline, making hallucination a measured metric rather than an assumed risk.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_ai_multi_provider_llm_orchestration"
          ]
        },
        {
          "id": "jeremy_domain_ai_multi_provider_llm_orchestration.b4",
          "text": "Built a Model Context Protocol (MCP) server exposing a provenance-attached experience corpus as queryable tools, with an append-only write path that verifies content re-parses before writing and records each immutable snapshot with a sha256 in a version ledger.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_ai_multi_provider_llm_orchestration"
          ]
        },
        {
          "id": "jeremy_domain_ai_multi_provider_llm_orchestration.b5",
          "text": "Architected an evidence-grounded generation pipeline spanning requirement clustering, evidence inventory and resolution, lexical and semantic retrieval, capability reduction, and validation, with explicit human admission gates between stages.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_ai_multi_provider_llm_orchestration"
          ]
        }
      ]
    },
    {
      "id": "jeremy_domain_langgraph_reference_runtime",
      "organization": "Independent / Domain",
      "roleContext": [
        "Sole architect, specification author, and orchestrator",
        "Independent protocol implementation project",
        "Separation-of-powers multi-agent development process",
        "Python reference runtime for the Domain protocol"
      ],
      "timePeriod": "2026-07-29 – 2026-07-30 (repository re-verified by direct execution 2026-08-02)",
      "themes": [
        "protocol_design",
        "deterministic_systems",
        "multi_agent_orchestration",
        "separation_of_powers",
        "langgraph",
        "python_backend",
        "verification_and_validation",
        "mutation_testing",
        "fault_injection",
        "crash_recovery",
        "content_addressed_state",
        "provenance_and_auditability",
        "specification_authorship",
        "reference_implementation",
        "provider_neutral_architecture",
        "agentic_systems"
      ],
      "roleFit": {
        "strongest": [
          "AI Platform Engineer",
          "Agent Infrastructure Engineer",
          "Forward Deployed Engineer",
          "AI Solutions Engineer",
          "Developer Tools Product",
          "Technical Product Strategy (AI)"
        ],
        "secondary": [
          "Solutions Architect",
          "Backend Systems Engineer",
          "Technical Program Manager (AI)",
          "Staff Engineer, Platform"
        ]
      },
      "caution": [
        "This is Jeremy's own independent project, not a client engagement, employer deliverable, or commercial deployment. It is a reference implementation of his own protocol — never describe it as shipped, adopted, or used by anyone else.",
        "The 'conforming' verdict is produced by the project's own Verifier role against the project's own validation constraints. It is internally rigorous and re-executable, but it is not third-party certification, an external audit, or an industry standard. Do not imply outside validation.",
        "The mutation score of 9/9 (100%) covers the 9 mutations declared critical by the project's own validation constraints. It is NOT a whole-codebase mutation score. Always say 'critical mutations' — never claim 100% mutation coverage of the codebase.",
        "Git history is not the evidence trail: the repository has only 2 commits ('Initial commit' and a squashed 'init commit at v32'). The 19-iteration implementer chain and 25 resolved defects live in implementation-frontier.yaml and validation-report.json, not in git. Do not cite commit counts as development evidence.",
        "Solo project with no external users, no production traffic, no uptime or SLA history, and no downstream adopters. Do not imply team size, scale, or operational maturity.",
        "The runtime is deliberately offline and requires no model credentials — it exercises the protocol with deterministic role stubs. Do not describe it as running live LLM agents in production; the optional model adapter gate (F) is recorded as not_required, meaning that path was not exercised.",
        "Test and verification figures (88 tests, 50 edge cases, 9 critical mutations, 25 defects) were re-verified on 2026-08-02 and are accurate as of that date. Re-run the suite before citing them externally.",
        "This is a distinct project from the TypeScript multi-provider LLM orchestration system recorded in jeremy_domain_ai_multi_provider_llm_orchestration. Same Domain program lineage, different language, repository, and purpose — do not merge their statistics or describe them as one codebase."
      ],
      "bullets": [
        {
          "id": "jeremy_domain_langgraph_reference_runtime.b1",
          "text": "Built a provider-neutral deterministic reference runtime for an agent-orchestration protocol in Python on LangGraph (3,694 lines across 50 modules, 2,317 lines of tests), separating a deterministic protocol kernel from the execution framework so that snapshots remain valid without LangGraph or a database.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_langgraph_reference_runtime"
          ]
        },
        {
          "id": "jeremy_domain_langgraph_reference_runtime.b2",
          "text": "Designed a separation-of-powers agent architecture in which an orchestrator dispatches to Author, Implementer, and Verifier roles but is barred from authoring, implementing, repairing, or manufacturing conformance — every role response carrying its owned writes, evidence, base frontier hash, and unresolved questions.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_langgraph_reference_runtime"
          ]
        },
        {
          "id": "jeremy_domain_langgraph_reference_runtime.b3",
          "text": "Established correctness with an executable 50-case edge matrix (50/50 passing, machine-checked against a declared ledger), 9/9 critical mutations killed with zero survivors, and seven fault-injection crash/resume scenarios covering pre- and post-commit failures.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_langgraph_reference_runtime"
          ]
        },
        {
          "id": "jeremy_domain_langgraph_reference_runtime.b4",
          "text": "Authored ~4,500 lines of specification across five canonical documents pinned by sha256 in an author frontier with an explicit authority ordering and recorded conflict assessment, then drove 19 auditable implementer iterations to a conforming verdict with 25 defects resolved.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_langgraph_reference_runtime"
          ]
        },
        {
          "id": "jeremy_domain_langgraph_reference_runtime.b5",
          "text": "Enforced the distinction between execution facts and protocol facts — a framework checkpoint, a passing test, or graph termination is never a protocol snapshot — with atomic admission of exactly one portable snapshot at a coherent, conforming, settled frontier.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_langgraph_reference_runtime"
          ]
        }
      ]
    },
    {
      "id": "jeremy_domain_corus_chatbot_filesystem_runtime_contract",
      "organization": "Independent / Domain",
      "roleContext": [
        "Sole author of the runtime contract and acceptance suite",
        "Independent AI runtime specification project",
        "Specification-and-tests-first design, ahead of implementation"
      ],
      "timePeriod": "2026-06-27 (files inspected 2026-08-02)",
      "themes": [
        "runtime_contract_design",
        "event_sourcing",
        "append_only_ledger",
        "replay_based_state",
        "acceptance_test_authorship",
        "specification_first_design",
        "ai_safety_boundaries",
        "human_in_the_loop_gating",
        "versioned_promotion",
        "crash_recovery",
        "conversational_runtimes",
        "agentic_systems"
      ],
      "roleFit": {
        "strongest": [
          "AI Solutions Engineer",
          "Technical Product Strategy (AI)",
          "AI Platform Engineer",
          "Developer Tools Product",
          "Forward Deployed Engineer"
        ],
        "secondary": [
          "Solutions Architect",
          "Technical Program Manager (AI)",
          "AI Product Operations"
        ]
      },
      "caution": [
        "This is a specification and an acceptance contract. No implementation of this runtime was located during inspection — describe it as a designed and tested-by-contract runtime, never as a built or running system, and never claim the acceptance suite passes.",
        "Version numbers are early (schema_version 0.1.0 throughout). This is an early-stage design, not a settled or released contract.",
        "The files live in the Tempo/StratOS Obsidian vault but belong to the Domain/Corus lineage, not to StratOS. Do not describe this as part of the strategy-modeling work — the shared folder is incidental.",
        "Solo project, no external users, no adopters, no production use. Do not imply scale, team, or deployment.",
        "The seven test cases were verified as declared in tests.md by direct inspection. They were not executed — there is no runtime to execute them against.",
        "This is distinct from both the TypeScript LLM orchestration system and the Python domain-v1 runtime. Same Corus/Domain program lineage, separate artifact — do not merge their statistics."
      ],
      "bullets": [
        {
          "id": "jeremy_domain_corus_chatbot_filesystem_runtime_contract.b1",
          "text": "Authored a runtime contract letting a chatbot maintain a durable ledger-backed project filesystem inside a conversation — append-only JSONL memory, state regenerated by replay rather than edited in place, and versioned promotion with a declared recovery path.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_corus_chatbot_filesystem_runtime_contract"
          ]
        },
        {
          "id": "jeremy_domain_corus_chatbot_filesystem_runtime_contract.b2",
          "text": "Specified an assistant behavior layer whose defining constraints are prohibitions: it may notice candidate state changes, propose a ledger patch, and render verification surfaces, but may never silently update files or mark its own candidate events as admitted.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_corus_chatbot_filesystem_runtime_contract"
          ]
        },
        {
          "id": "jeremy_domain_corus_chatbot_filesystem_runtime_contract.b3",
          "text": "Paired the contract with a seven-case golden acceptance suite covering boot, ledger seeding, state projection, behavior rules, runtime write, promotion, and recovery — written as an acceptance contract before implementation rather than as tests derived from it.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_corus_chatbot_filesystem_runtime_contract"
          ]
        },
        {
          "id": "jeremy_domain_corus_chatbot_filesystem_runtime_contract.b4",
          "text": "Designed boot validation to fail closed: partial instantiation is prohibited, and any manifest that is malformed, duplicated, incomplete, or requests an unsafe external action renders a verification notice instead of a partly-built filesystem.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#jeremy_domain_corus_chatbot_filesystem_runtime_contract"
          ]
        }
      ]
    },
    {
      "id": "tempo_stratos_v5_governed_decision_product",
      "organization": "Independent / Tempo",
      "roleContext": [
        "Sole product manager and model owner",
        "Directed AI agents across research, implementation, and validation while retaining schema and claim authority",
        "Independent 0-to-1 product project",
        "Second phase of the Tempo/StratOS work, following the early framework-modeling prototype"
      ],
      "timePeriod": "2026-03 – 2026-07 (v5.1 validator re-executed and artifacts re-inspected 2026-08-02)",
      "themes": [
        "product_discovery_through_falsification",
        "epistemic_product_design",
        "evaluation_of_probabilistic_output",
        "schema_and_data_contract_ownership",
        "agent_orchestration_with_human_accountability",
        "governance_floors",
        "uncertainty_quantification",
        "release_judgment",
        "executable_validation",
        "synthetic_fixture_design",
        "consulting_ip_productization",
        "knowledge_architecture",
        "removing_invalid_constructs",
        "executive_facilitation_design",
        "computational_strategy",
        "obsidian_knowledge_systems"
      ],
      "roleFit": {
        "strongest": [
          "Senior Product Manager, AI Foundry",
          "AI Product Strategy",
          "Internal AI Platform Product",
          "Technical Product Manager (AI)",
          "Product Systems Architect",
          "Consulting Knowledge Systems"
        ],
        "secondary": [
          "AI Product Operations",
          "Knowledge Management Product",
          "Strategy and Innovation Operations",
          "Technical Program Manager (AI)"
        ]
      },
      "caution": [
        "Describe StratOS as an active prototype and a technically implemented 0-to-1 concept, never as a deployed, adopted, or production product. There is no user adoption, no measured decision improvement, no time saved, no accuracy against ground truth, no repeated workflow use, and no client impact.",
        "The validator passes as of 2026-08-02 at v5.1 — this reversed a defect that was open in July 2026. Re-run it before citing; do not cite the July documentation, which records it as failing.",
        "Artifact drift is STILL an open defect as of 2026-08-02: the Prophet profile computes ~$330K RPE while the generated workshop deck still shows $276K. Never claim all generated artifacts are current or reconciled. This is honestly usable as an example of release discipline gaps, not as a strength.",
        "Never claim the model is objective or that the audit measures organizational performance. Positions are disclosed judgments with rationales, not measurements. The benchmark does not rank firms.",
        "Do not present derived organizational scores, heuristic weights, posture weights, or word-to-number mappings as validated or outcome-calibrated business measures. They are asserted, and the project's own documentation says so.",
        "The firm assessments (Prophet, McKinsey, Deloitte, Accenture, Gartner, EPAM, Slalom, GLG, FTI, Alvarez & Marsal) are desk audits built from public and estimated data, explicitly framed as contestable hypotheses. Never present any of them as an accurate internal diagnosis of a real company. Prophet's revenue figure in particular is an aggregator estimate spanning $204M–$259M.",
        "Do not claim agents operated autonomously. The documented operating model is Jeremy directing two to three concurrent workstreams with a hand in every schema; the case study states the formal researcher/critic/engineer role model is a retrospective description, not how early tasks were actually named.",
        "The first external domain review was SCHEDULED for 2026-07-27. No evidence was found that it occurred or what came of it. Do not claim external validation, expert endorsement, or review findings.",
        "V1 through V5 were not user-driven iterations. They were driven by Jeremy's own falsification of his prior models. Do not imply user research drove the sequence — the case study identifies workflow research and user interviews as the NEXT phase, not completed work.",
        "The Prophet connection is an origin story (a March 2026 conversation with Partner Jonathan Chajet about a prospecting tool) and a target role, not a client engagement, contract, or working relationship. Never describe Prophet as a client.",
        "This is the second phase of the Tempo work. The earlier prototype is recorded separately as tempo_strategy_framework_model; the two are complementary, and the v1 failure modes are what motivated this phase. Do not merge or double-count their claims."
      ],
      "bullets": [
        {
          "id": "tempo_stratos_v5_governed_decision_product.b1",
          "text": "Led a 0-to-1 AI product through five generations from a deterministic scoring prototype to a governed C-suite architecture audit, where each generation removed a specific class of unjustified certainty — hand-set coefficients, favorable defaults for missing evidence, and model-invented target states.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_stratos_v5_governed_decision_product"
          ]
        },
        {
          "id": "tempo_stratos_v5_governed_decision_product.b2",
          "text": "Designed a product contract that keeps four claims separate and refuses to collapse them into one score: where a firm sits (descriptive, never a grade), how well the product knows (confidence, which changes interval width only), whether material choices were made, and whether non-compensating viability floors are cleared — with only the last able to decide a verdict.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_stratos_v5_governed_decision_product"
          ]
        },
        {
          "id": "tempo_stratos_v5_governed_decision_product.b3",
          "text": "Removed Coherence, the model's most persuasive output, after determining a desk audit cannot observe a firm's intended target and the system was grading firms against an invented intention; replaced it with Layer Balance and a Commitment index, and deferred Coherence to an inside-access tier where the customer defines the goal.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_stratos_v5_governed_decision_product"
          ]
        },
        {
          "id": "tempo_stratos_v5_governed_decision_product.b4",
          "text": "Established a well-formedness test requiring both poles of any strategic tension to have a paid executive advocate, using it to retire 'Autonomous Agency' and convert agentic governance into a non-compensating floor owned by the Chief Risk Officer — so a strategic strength cannot offset unsafe autonomous behavior.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_stratos_v5_governed_decision_product"
          ]
        },
        {
          "id": "tempo_stratos_v5_governed_decision_product.b5",
          "text": "Built executable evaluation for a qualitative model: a Ruby validator over 17 canonical sources and 10 firm profiles, plus 3 synthetic fixtures pinning the PASS, FLAG, and SURVIVAL branches, with invariants asserting that confidence never moves position and that descriptive indices never reach the verdict.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_stratos_v5_governed_decision_product"
          ]
        },
        {
          "id": "tempo_stratos_v5_governed_decision_product.b6",
          "text": "Directed ChatGPT, Codex, Gemini, and Claude Code across two to three parallel workstreams — selecting tools by type of uncertainty rather than by role label — while retaining authorship of every schema, because schemas control the deterministic downstream workflow.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_stratos_v5_governed_decision_product"
          ]
        },
        {
          "id": "tempo_stratos_v5_governed_decision_product.b7",
          "text": "Applied a formal program protocol to the project's own status, publishing outcome measures with candid labels (met_with_drift, unmet, unproven) including an unresolved artifact-reconciliation defect and the absence of any adoption or workflow-validation evidence.",
          "evidenceRefs": [],
          "sourceRefs": [
            "engagements.yaml#tempo_stratos_v5_governed_decision_product"
          ]
        }
      ]
    }
  ],
  "skills": [],
  "education": [
    {
      "degree": "Bachelor's Degree, minor in Mathematics"
    }
  ],
  "projects": []
};
