import { CASE_PROFILE_SCHEMA, defineCaseProfile } from './profile';

export const ADOBE_CREATIVE_CLOUD = defineCaseProfile({
  schema: CASE_PROFILE_SCHEMA,
  id: 'adobe-creative-cloud-2012-2016',
  version: '1.0.0',
  company: { name: 'Adobe Systems Incorporated', ticker: 'ADBE', exchange: 'NASDAQ' },
  case: {
    name: 'Creative Cloud business-model transition',
    scope: 'Adobe creative products from the May 2012 Creative Cloud launch through fiscal 2016, when perpetual creative revenue had become immaterial.',
    announcedAt: '2012-05',
    status: 'completed',
    commitment: 'Move the creative-products business from perpetual licenses toward subscription access, recurring revenue, and continuously delivered cloud functionality.',
    targets: [
      {
        id: 'subscription-transition',
        label: 'Increase the portion of creative revenue derived from subscriptions; no public completion deadline was stated in the launch-period filing.',
        evidence: [{ sourceId: 'adobe-2012-10k', locator: 'Risk Factors, cloud strategy; Creative Cloud launch discussion' }],
      },
    ],
  },
  scoring: {
    status: 'scored',
    rubricVersion: '0.2.0',
    scorecardId: 'adobe-creative-cloud-outcome-retrodiction-2017-v0.2',
    scope: 'outcome-calibrated-retrodiction',
    reason: 'The outcome-calibrated scorecard uses adoption, recurring-revenue, ARR, and transition-duration evidence while preserving the commitment-only view separately.',
  },
  sources: [
    {
      id: 'adobe-2012-10k',
      title: 'Adobe Systems Incorporated Fiscal 2012 Form 10-K',
      publisher: 'U.S. Securities and Exchange Commission',
      kind: 'filing',
      publishedAt: '2013-01-22',
      url: 'https://www.sec.gov/Archives/edgar/data/796343/000079634313000008/adbe10kfy12.htm',
    },
    {
      id: 'adobe-2013-10k',
      title: 'Adobe Systems Incorporated Fiscal 2013 Form 10-K',
      publisher: 'U.S. Securities and Exchange Commission',
      kind: 'filing',
      publishedAt: '2014-01-21',
      url: 'https://www.sec.gov/Archives/edgar/data/796343/000079634314000004/adbe10kfy13.htm',
    },
    {
      id: 'adobe-2016-10k',
      title: 'Adobe Systems Incorporated Fiscal 2016 Form 10-K',
      publisher: 'U.S. Securities and Exchange Commission',
      kind: 'filing',
      publishedAt: '2017-01-20',
      url: 'https://www.sec.gov/Archives/edgar/data/796343/000079634317000031/adbe10kfy16.htm',
    },
  ],
  facts: [
    {
      id: 'creative-cloud-launched',
      statement: 'Adobe launched the subscription-based Creative Cloud offering in May 2012.',
      observedAt: '2012-05',
      origin: 'reported',
      evidence: [{ sourceId: 'adobe-2012-10k', locator: 'Cloud strategy and subscription renewal discussion' }],
    },
    {
      id: 'transition-risks-disclosed',
      statement: 'Adobe disclosed that the transition could reduce near-term revenue, require continued product and cloud-operations investment, and create pricing, adoption, renewal, partner, and execution risks.',
      observedAt: '2012-11-30',
      origin: 'reported',
      evidence: [{ sourceId: 'adobe-2012-10k', locator: 'Risk Factors: increased emphasis on a cloud strategy' }],
    },
    {
      id: 'renewal-data-not-yet-available',
      statement: 'At fiscal 2012 year-end, Adobe said meaningful annual subscription-renewal data was not yet available because the offering had not reached its first anniversary.',
      observedAt: '2012-11-30',
      origin: 'reported',
      evidence: [{ sourceId: 'adobe-2012-10k', locator: 'Creative Cloud subscription renewal discussion' }],
    },
    {
      id: 'cloud-only-innovation-policy',
      statement: 'In May 2013 Adobe announced that new creative-product innovations and features would be delivered exclusively to Creative Cloud subscribers and that CS6 would be the last major perpetual-license update.',
      observedAt: '2013-05-01',
      origin: 'reported',
      evidence: [{ sourceId: 'adobe-2013-10k', locator: 'Business, Digital Media strategy' }],
    },
    {
      id: 'paid-subscribers-2013',
      statement: 'Adobe exited fiscal 2013 with 1.4 million paid Creative Cloud subscriptions, up from 0.3 million at fiscal 2012 year-end.',
      observedAt: '2013-11-29',
      origin: 'reported',
      metric: { value: 1.4, unit: 'million paid subscriptions' },
      evidence: [{ sourceId: 'adobe-2013-10k', locator: 'Creative Cloud ARR and subscription discussion' }],
    },
    {
      id: 'creative-arr-2013',
      statement: 'Creative ARR reached $768 million at fiscal 2013 year-end, up from $155 million at fiscal 2012 year-end.',
      observedAt: '2013-11-29',
      origin: 'reported',
      metric: { value: 768, unit: 'USD millions ARR' },
      evidence: [{ sourceId: 'adobe-2013-10k', locator: 'Creative ARR definition and results' }],
    },
    {
      id: 'subscription-revenue-2016',
      statement: 'Adobe reported $4.5848 billion of subscription revenue in fiscal 2016.',
      observedAt: '2016-12-02',
      origin: 'reported',
      metric: { value: 4.5848, unit: 'USD billions subscription revenue' },
      evidence: [{ sourceId: 'adobe-2016-10k', locator: 'Revenue table, fiscal 2016 compared with 2015 and 2014' }],
    },
    {
      id: 'subscription-share-2016',
      statement: 'Subscription revenue represented 78% of Adobe total revenue in fiscal 2016.',
      observedAt: '2016-12-02',
      origin: 'reported',
      metric: { value: 78, unit: 'percent of total revenue' },
      evidence: [{ sourceId: 'adobe-2016-10k', locator: 'Revenue table, percentage of total revenue' }],
    },
    {
      id: 'digital-media-arr-2016',
      statement: 'Digital Media ARR reached $4.01 billion at fiscal 2016 year-end, up 39% from $2.88 billion at fiscal 2015 year-end.',
      observedAt: '2016-12-02',
      origin: 'reported',
      metric: { value: 4.01, unit: 'USD billions ARR' },
      evidence: [{ sourceId: 'adobe-2016-10k', locator: 'Financial Performance Summary for Fiscal 2016' }],
    },
    {
      id: 'perpetual-creative-immaterial',
      statement: 'Adobe reported that perpetual licensing revenue from creative products had become immaterial by fiscal 2016.',
      observedAt: '2016-12-02',
      origin: 'reported',
      evidence: [{ sourceId: 'adobe-2016-10k', locator: 'Business, Digital Media and Creative Cloud strategy' }],
    },
    {
      id: 'paid-subscriber-increase-2013',
      statement: 'Paid Creative Cloud subscriptions increased by 1.1 million from fiscal 2012 year-end to fiscal 2013 year-end.',
      observedAt: '2013-11-29',
      origin: 'derived',
      metric: { value: 1.1, unit: 'million paid subscriptions increase' },
      calculation: '1.4 million fiscal 2013 paid subscriptions − 0.3 million fiscal 2012 paid subscriptions = 1.1 million.',
      evidence: [{ sourceId: 'adobe-2013-10k', locator: 'Creative Cloud subscription discussion, 2013 and 2012 year-end counts' }],
    },
    {
      id: 'paid-subscriber-multiple-2013',
      statement: 'Fiscal 2013 year-end paid Creative Cloud subscriptions were approximately 4.67 times the fiscal 2012 year-end count.',
      observedAt: '2013-11-29',
      origin: 'derived',
      metric: { value: 4.6667, unit: 'times fiscal 2012 paid subscriptions' },
      calculation: '1.4 million / 0.3 million = 4.6667.',
      evidence: [{ sourceId: 'adobe-2013-10k', locator: 'Creative Cloud subscription discussion, 2013 and 2012 year-end counts' }],
    },
    {
      id: 'creative-arr-increase-2013',
      statement: 'Creative ARR increased by $613 million from fiscal 2012 year-end to fiscal 2013 year-end.',
      observedAt: '2013-11-29',
      origin: 'derived',
      metric: { value: 613, unit: 'USD millions ARR increase' },
      calculation: '$768 million fiscal 2013 Creative ARR − $155 million fiscal 2012 Creative ARR = $613 million.',
      evidence: [{ sourceId: 'adobe-2013-10k', locator: 'Creative ARR discussion, 2013 and 2012 year-end values' }],
    },
    {
      id: 'subscription-majority-surplus-2016',
      statement: 'Subscription revenue exceeded a simple majority of Adobe revenue by 28 percentage points in fiscal 2016.',
      observedAt: '2016-12-02',
      origin: 'derived',
      metric: { value: 28, unit: 'percentage points above 50% revenue share' },
      calculation: '78% subscription share − 50% majority threshold = 28 percentage points.',
      evidence: [{ sourceId: 'adobe-2016-10k', locator: 'Revenue table, percentage of total revenue' }],
    },
    {
      id: 'implied-total-revenue-2016',
      statement: 'The reported subscription revenue and 78% share imply approximately $5.878 billion of total fiscal 2016 revenue.',
      observedAt: '2016-12-02',
      origin: 'derived',
      metric: { value: 5.87795, unit: 'USD billions implied total revenue' },
      calculation: '$4.5848 billion subscription revenue / 78% = approximately $5.87795 billion; the result inherits rounding from the reported share.',
      evidence: [{ sourceId: 'adobe-2016-10k', locator: 'Revenue table, subscription revenue and percentage of total' }],
    },
    {
      id: 'digital-media-arr-increase-2016',
      statement: 'Digital Media ARR increased by $1.13 billion during fiscal 2016.',
      observedAt: '2016-12-02',
      origin: 'derived',
      metric: { value: 1.13, unit: 'USD billions ARR increase' },
      calculation: '$4.01 billion fiscal 2016 Digital Media ARR − $2.88 billion fiscal 2015 Digital Media ARR = $1.13 billion.',
      evidence: [{ sourceId: 'adobe-2016-10k', locator: 'Financial Performance Summary for Fiscal 2016' }],
    },
    {
      id: 'transition-duration-months',
      statement: 'The observable transition from the May 2012 launch to the fiscal 2016 year-end state lasted approximately 55 months.',
      observedAt: '2016-12-02',
      origin: 'derived',
      metric: { value: 55, unit: 'months, approximate observed transition duration' },
      calculation: 'May 2012 to December 2016 is approximately four years and seven months, or 55 months.',
      evidence: [
        { sourceId: 'adobe-2012-10k', locator: 'Creative Cloud May 2012 launch discussion' },
        { sourceId: 'adobe-2016-10k', locator: 'Fiscal 2016 year-end and perpetual creative revenue discussion' },
      ],
    },
  ],
  snapshots: [
    {
      id: 'commitment-2013-01-22',
      label: 'Launch-period evidence available',
      phase: 'commitment',
      knowledgeCutoff: '2013-01-22',
      factRefs: ['creative-cloud-launched', 'transition-risks-disclosed', 'renewal-data-not-yet-available'],
      systems: {
        discernment: { status: 'evidenced', confidence: 'medium', summary: 'Adobe articulated the intended model and disclosed material counter-risks rather than presenting adoption as settled.', factRefs: ['transition-risks-disclosed', 'renewal-data-not-yet-available'], unknowns: ['Internal thresholds for continuing or changing the transition'] },
        invention: { status: 'evidenced', confidence: 'medium', summary: 'Creative Cloud introduced subscription access and continuous cloud functionality as a new delivery and business model.', factRefs: ['creative-cloud-launched'], unknowns: ['Early cohort adoption and product-level use'] },
        operations: { status: 'inferred', confidence: 'medium', summary: 'The model required scalable cloud operations and new delivery processes, but launch-period service performance was not reported.', factRefs: ['transition-risks-disclosed'], unknowns: ['Service reliability', 'Deployment cycle time', 'Support load'] },
        execution: { status: 'inferred', confidence: 'low', summary: 'The subscription offering had shipped, but the public record did not yet contain a complete adoption-and-feedback cycle.', factRefs: ['creative-cloud-launched', 'renewal-data-not-yet-available'], unknowns: ['Renewal', 'Release failure rate', 'Rollback and assurance controls'] },
        advantage: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The recurring-revenue thesis was explicit, but launch-period evidence did not yet prove durable customer or economic value.', factRefs: ['transition-risks-disclosed'], unknowns: ['ARR trajectory', 'Retention', 'Customer expansion and economics'] },
        resource: { status: 'inferred', confidence: 'medium', summary: 'Adobe expected near-term revenue deferral while continuing to fund product development and cloud operations.', factRefs: ['transition-risks-disclosed'], unknowns: ['Investment envelope', 'Cash-flow trough', 'Critical staffing capacity'] },
      },
      constraints: {
        people: { status: 'inferred', confidence: 'low', summary: 'Adobe identified the need for a scalable organization and technical, sales, compliance, and cloud capabilities.', factRefs: ['transition-risks-disclosed'], unknowns: ['Critical-role counts', 'Hiring time', 'Team utilization'] },
        finance: { status: 'evidenced', confidence: 'medium', summary: 'Revenue deferral and continued investment were explicitly disclosed financial consequences of the model change.', factRefs: ['transition-risks-disclosed'], unknowns: ['Loss tolerance', 'Funding peak', 'Payback threshold'] },
        time: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'No public completion deadline was attached to the transition.', factRefs: [], unknowns: ['Internal milestones', 'Required migration rate', 'Decision horizon'] },
        risk: { status: 'evidenced', confidence: 'medium', summary: 'Adobe disclosed adoption, renewal, pricing, reliability, partner, and execution risks before outcome evidence was available.', factRefs: ['transition-risks-disclosed', 'renewal-data-not-yet-available'], unknowns: ['Risk limits', 'Specific mitigations and gates'] },
      },
    },
    {
      id: 'update-2014-01-21',
      label: 'Subscription adoption and commitment deepen',
      phase: 'material-update',
      knowledgeCutoff: '2014-01-21',
      factRefs: ['cloud-only-innovation-policy', 'paid-subscribers-2013', 'creative-arr-2013'],
      systems: {
        discernment: { status: 'evidenced', confidence: 'medium', summary: 'Adobe deepened the transition after observing subscriber and ARR growth, while ending major perpetual-version innovation.', factRefs: ['cloud-only-innovation-policy', 'paid-subscribers-2013', 'creative-arr-2013'], unknowns: ['Decision rule connecting adoption evidence to exclusivity'] },
        invention: { status: 'evidenced', confidence: 'high', summary: 'Exclusive cloud innovation and rapid paid-subscription growth demonstrate adoption of the new offering model.', factRefs: ['cloud-only-innovation-policy', 'paid-subscribers-2013'], unknowns: ['Cohort retention and engagement'] },
        operations: { status: 'inferred', confidence: 'medium', summary: 'Supporting 1.4 million paid subscriptions implies scaled billing and service operations, though quality metrics remain undisclosed.', factRefs: ['paid-subscribers-2013'], unknowns: ['Availability', 'Support cycle time', 'Unit service cost'] },
        execution: { status: 'evidenced', confidence: 'medium', summary: 'The case now contains a release-and-adoption cycle: launch, exclusive feature policy, paid adoption, and ARR evidence.', factRefs: ['cloud-only-innovation-policy', 'paid-subscribers-2013', 'creative-arr-2013'], unknowns: ['Renewal and failure-rate evidence'] },
        advantage: { status: 'evidenced', confidence: 'medium', summary: 'Subscriber and ARR growth provide boundary and economic evidence, although durability was not yet established.', factRefs: ['paid-subscribers-2013', 'creative-arr-2013'], unknowns: ['Long-run retention', 'Margin and competitive response'] },
        resource: { status: 'inferred', confidence: 'medium', summary: 'ARR was accumulating while Adobe was still funding the transition; the source does not isolate the program investment.', factRefs: ['creative-arr-2013'], unknowns: ['Program capex and opex', 'Cash conversion', 'Capacity renewal'] },
      },
      constraints: {
        people: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'Adoption is visible, but workforce load and skill coverage remain undisclosed.', factRefs: [], unknowns: ['Cloud-operations staffing', 'Sales transition capacity', 'Support load'] },
        finance: { status: 'inferred', confidence: 'medium', summary: 'ARR growth is visible, but revenue recognition and transition investment still separate bookings from realized financial return.', factRefs: ['creative-arr-2013'], unknowns: ['Transition cash flow', 'Contribution margin', 'Investment payback'] },
        time: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'Progress is measurable, but the commitment still has no public completion deadline.', factRefs: ['paid-subscribers-2013'], unknowns: ['Required completion date', 'Migration cadence threshold'] },
        risk: { status: 'inferred', confidence: 'medium', summary: 'Cloud-only innovation increased commitment and switching exposure while adoption evidence strengthened.', factRefs: ['cloud-only-innovation-policy', 'paid-subscribers-2013'], unknowns: ['Churn', 'Customer concentration', 'Service incidents'] },
      },
    },
    {
      id: 'outcome-2017-01-20',
      label: 'Subscription model established',
      phase: 'outcome',
      knowledgeCutoff: '2017-01-20',
      factRefs: [
        'creative-cloud-launched',
        'transition-risks-disclosed',
        'renewal-data-not-yet-available',
        'cloud-only-innovation-policy',
        'paid-subscribers-2013',
        'creative-arr-2013',
        'subscription-revenue-2016',
        'subscription-share-2016',
        'digital-media-arr-2016',
        'perpetual-creative-immaterial',
        'paid-subscriber-increase-2013',
        'paid-subscriber-multiple-2013',
        'creative-arr-increase-2013',
        'subscription-majority-surplus-2016',
        'implied-total-revenue-2016',
        'digital-media-arr-increase-2016',
        'transition-duration-months',
      ],
      systems: {
        discernment: { status: 'evidenced', confidence: 'medium', summary: 'The successive launch, policy change, metric adoption, and economic results show a commitment reinforced by observed evidence.', factRefs: ['cloud-only-innovation-policy', 'digital-media-arr-2016'], unknowns: ['Internal rejected alternatives'] },
        invention: { status: 'evidenced', confidence: 'high', summary: 'The subscription offering became the dominant creative delivery model and displaced perpetual creative revenue.', factRefs: ['subscription-share-2016', 'perpetual-creative-immaterial'], unknowns: ['Product-level adoption dispersion'] },
        operations: { status: 'inferred', confidence: 'medium', summary: 'Revenue at subscription scale implies functioning recurring billing and cloud delivery, but operational reliability is not quantified here.', factRefs: ['subscription-revenue-2016'], unknowns: ['Availability', 'Support efficiency', 'Release cadence'] },
        execution: { status: 'evidenced', confidence: 'high', summary: 'The transition produced repeated releases, adoption, and measurable recurring economic evidence over four fiscal years.', factRefs: ['creative-cloud-launched', 'paid-subscribers-2013', 'digital-media-arr-2016'], unknowns: ['Detailed cycle-time distribution'] },
        advantage: { status: 'evidenced', confidence: 'high', summary: 'A 78% subscription revenue mix and $4.01 billion of Digital Media ARR demonstrate externally realized and recurring economic value.', factRefs: ['subscription-share-2016', 'digital-media-arr-2016'], unknowns: ['Causal contribution versus market growth'] },
        resource: { status: 'evidenced', confidence: 'medium', summary: 'The business moved from disclosed revenue deferral risk to a large recurring-revenue base, supporting renewal of invested capacity.', factRefs: ['transition-risks-disclosed', 'subscription-revenue-2016', 'digital-media-arr-2016'], unknowns: ['Full transition ROIC', 'Cumulative investment'] },
      },
      constraints: {
        people: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The selected filings do not quantify critical-role capacity through the transition.', factRefs: [], unknowns: ['Role-specific headcount', 'Turnover', 'Workload and skill redundancy'] },
        finance: { status: 'evidenced', confidence: 'medium', summary: 'The recurring-revenue base is established, but a case-specific investment and ROIC calculation still requires cost allocation.', factRefs: ['subscription-revenue-2016', 'digital-media-arr-2016'], unknowns: ['Cumulative program cost', 'Case-specific return on invested capital'] },
        time: { status: 'evidenced', confidence: 'medium', summary: 'The observable transition window runs from the May 2012 launch to the fiscal 2016 state in which perpetual creative revenue was immaterial.', factRefs: ['creative-cloud-launched', 'perpetual-creative-immaterial'], unknowns: ['Original internal deadline'] },
        risk: { status: 'evidenced', confidence: 'medium', summary: 'The adoption and revenue outcomes reduced launch-period market-acceptance uncertainty, although operating and concentration risks remained.', factRefs: ['transition-risks-disclosed', 'subscription-share-2016'], unknowns: ['Incident history', 'Churn sensitivity', 'Platform concentration'] },
      },
    },
  ],
});
