import { CASE_PROFILE_SCHEMA, defineCaseProfile } from './profile';

export const DOMINOS_2025_GROWTH = defineCaseProfile({
  schema: CASE_PROFILE_SCHEMA,
  id: 'dominos-growth-2018-2025',
  version: '1.0.0',
  company: { name: "Domino's Pizza, Inc.", ticker: 'DPZ', exchange: 'NASDAQ' },
  case: {
    name: '2025 global store and retail-sales commitment',
    scope: "Domino's global system from the fiscal 2018 commitment through fiscal 2025 results, including franchised and company-owned stores.",
    announcedAt: '2018',
    status: 'completed',
    commitment: 'Reach 25,000 stores and more than $25 billion in global retail sales by the end of 2025 while maintaining franchisee returns and operational simplicity.',
    targets: [
      {
        id: 'global-store-count-2025',
        label: 'Operate 25,000 stores globally by the end of 2025.',
        deadline: '2025-12-31',
        target: { value: 25000, unit: 'stores' },
        evidence: [{ sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, 2025 goals' }],
      },
      {
        id: 'global-retail-sales-2025',
        label: 'Generate more than $25 billion in annual global retail sales by the end of 2025.',
        deadline: '2025-12-31',
        target: { value: 25, unit: 'USD billions global retail sales' },
        evidence: [{ sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, 2025 goals' }],
      },
    ],
  },
  scoring: {
    status: 'scored',
    rubricVersion: '0.2.0',
    scorecardId: 'dominos-growth-outcome-retrodiction-2026-v0.2',
    scope: 'outcome-calibrated-retrodiction',
    reason: 'The outcome-calibrated scorecard places the explicit store and sales endpoint gaps while retaining continued growth as counter-evidence to a generic failure label.',
  },
  sources: [
    {
      id: 'dominos-2018-annual',
      title: "Domino's Pizza 2018 Annual Report",
      publisher: "Domino's Pizza, Inc.",
      kind: 'annual-report',
      publishedAt: '2019-02-21',
      url: 'https://ir.dominos.com/static-files/593a1150-28b1-49a9-8263-88710bb1237a',
    },
    {
      id: 'dominos-2019-10k',
      title: "Domino's Pizza Fiscal 2019 Form 10-K",
      publisher: 'U.S. Securities and Exchange Commission',
      kind: 'filing',
      publishedAt: '2020-02-20',
      url: 'https://www.sec.gov/Archives/edgar/data/1286681/000119312520042675/d796357d10k.htm',
    },
    {
      id: 'dominos-2025-results',
      title: "Domino's Pizza Announces Fourth Quarter and Fiscal 2025 Financial Results",
      publisher: "Domino's Pizza, Inc.",
      kind: 'earnings-release',
      publishedAt: '2026-02-23',
      url: 'https://ir.dominos.com/node/24181',
    },
  ],
  facts: [
    {
      id: 'target-stores-2025',
      statement: "Domino's set a goal of 25,000 global stores by the end of 2025.",
      observedAt: '2018',
      origin: 'reported',
      metric: { value: 25000, unit: 'stores' },
      evidence: [{ sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, 2025 goals' }],
    },
    {
      id: 'target-sales-2025',
      statement: "Domino's set a goal of more than $25 billion in global retail sales by the end of 2025.",
      observedAt: '2018',
      origin: 'reported',
      metric: { value: 25, unit: 'USD billions global retail sales' },
      evidence: [{ sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, 2025 goals' }],
    },
    {
      id: 'digital-sales-us-2018',
      statement: 'More than 65% of U.S. retail sales came through digital platforms in fiscal 2018.',
      observedAt: '2018-12-30',
      origin: 'reported',
      metric: { value: 65, unit: 'percent, lower bound' },
      evidence: [{ sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, technology and loyalty discussion' }],
    },
    {
      id: 'loyalty-users-2018',
      statement: "Domino's reported more than 20 million active Piece of the Pie Rewards users in fiscal 2018.",
      observedAt: '2018-12-30',
      origin: 'reported',
      metric: { value: 20, unit: 'million active loyalty users, lower bound' },
      evidence: [{ sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, technology and loyalty discussion' }],
    },
    {
      id: 'new-store-payback-2018',
      statement: "Domino's reported global average cash-on-cash payback on new-store investment of less than three years.",
      observedAt: '2018-12-30',
      origin: 'reported',
      metric: { value: 3, unit: 'years, upper bound' },
      evidence: [{ sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, franchisee economics' }],
    },
    {
      id: 'in-house-ordering-platform',
      statement: "Domino's reported that it decided in 2010 to develop and manage its online ordering platform internally.",
      observedAt: '2010',
      origin: 'reported',
      evidence: [{ sourceId: 'dominos-2019-10k', locator: 'Business, Technological Innovation' }],
    },
    {
      id: 'global-digital-sales-2019',
      statement: 'More than half of global retail sales were derived from digital channels in fiscal 2019.',
      observedAt: '2019-12-29',
      origin: 'reported',
      metric: { value: 50, unit: 'percent, lower bound' },
      evidence: [{ sourceId: 'dominos-2019-10k', locator: 'Business, Technological Innovation' }],
    },
    {
      id: 'actual-stores-2025',
      statement: "Domino's operated 22,142 stores at fiscal 2025 year-end.",
      observedAt: '2025-12-28',
      origin: 'reported',
      metric: { value: 22142, unit: 'stores' },
      evidence: [{ sourceId: 'dominos-2025-results', locator: 'Fourth quarter 2025 store counts' }],
    },
    {
      id: 'actual-sales-2025',
      statement: "Domino's reported $20.1268 billion of global retail sales in fiscal 2025.",
      observedAt: '2025-12-28',
      origin: 'reported',
      metric: { value: 20.1268, unit: 'USD billions global retail sales' },
      evidence: [{ sourceId: 'dominos-2025-results', locator: 'Fiscal 2025 operational and financial highlights, global retail sales' }],
    },
    {
      id: 'net-store-growth-2025',
      statement: "Domino's added 776 net stores globally during fiscal 2025.",
      observedAt: '2025-12-28',
      origin: 'reported',
      metric: { value: 776, unit: 'net stores' },
      evidence: [{ sourceId: 'dominos-2025-results', locator: 'Fiscal 2025 headline operational results' }],
    },
    {
      id: 'operating-income-growth-2025',
      statement: "Domino's income from operations increased 8.5% in fiscal 2025.",
      observedAt: '2025-12-28',
      origin: 'reported',
      metric: { value: 8.5, unit: 'percent year-over-year' },
      evidence: [{ sourceId: 'dominos-2025-results', locator: 'Fiscal 2025 headline financial results' }],
    },
    {
      id: 'store-target-attainment',
      statement: "Domino's finished fiscal 2025 at 88.568% of the stated 25,000-store endpoint.",
      observedAt: '2025-12-28',
      origin: 'derived',
      metric: { value: 88.568, unit: 'percent of target' },
      calculation: '22,142 actual stores / 25,000 target stores × 100.',
      evidence: [
        { sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, 2025 store goal' },
        { sourceId: 'dominos-2025-results', locator: 'Fourth quarter 2025 store counts' },
      ],
    },
    {
      id: 'sales-target-attainment',
      statement: "Domino's finished fiscal 2025 at 80.5072% of the stated $25 billion retail-sales endpoint.",
      observedAt: '2025-12-28',
      origin: 'derived',
      metric: { value: 80.5072, unit: 'percent of target' },
      calculation: '$20.1268 billion actual global retail sales / $25 billion target × 100.',
      evidence: [
        { sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, 2025 sales goal' },
        { sourceId: 'dominos-2025-results', locator: 'Fiscal 2025 operational and financial highlights, global retail sales' },
      ],
    },
    {
      id: 'store-target-shortfall',
      statement: "Domino's finished fiscal 2025 with 2,858 fewer stores than the stated 25,000-store endpoint.",
      observedAt: '2025-12-28',
      origin: 'derived',
      metric: { value: -2858, unit: 'stores versus target' },
      calculation: '22,142 actual stores − 25,000 target stores = -2,858 stores.',
      evidence: [
        { sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, 2025 store goal' },
        { sourceId: 'dominos-2025-results', locator: 'Fourth quarter 2025 store counts' },
      ],
    },
    {
      id: 'sales-target-shortfall',
      statement: "Domino's finished fiscal 2025 $4.8732 billion below the stated $25 billion global retail-sales endpoint.",
      observedAt: '2025-12-28',
      origin: 'derived',
      metric: { value: -4.8732, unit: 'USD billions global retail sales versus target' },
      calculation: '$20.1268 billion actual global retail sales − $25 billion target = -$4.8732 billion.',
      evidence: [
        { sourceId: 'dominos-2018-annual', locator: 'Shareholder letter, 2025 sales goal' },
        { sourceId: 'dominos-2025-results', locator: 'Fiscal 2025 global retail sales' },
      ],
    },
    {
      id: 'global-retail-sales-per-store-2025',
      statement: "Fiscal 2025 global retail sales averaged approximately $908,987 per year-end store as a system-scale proxy.",
      observedAt: '2025-12-28',
      origin: 'derived',
      metric: { value: 908987.44, unit: 'USD global retail sales per year-end store' },
      calculation: '$20.1268 billion global retail sales / 22,142 year-end stores = approximately $908,987; this is a system-scale proxy, not same-store unit economics.',
      evidence: [{ sourceId: 'dominos-2025-results', locator: 'Fiscal 2025 global retail sales and year-end store counts' }],
    },
  ],
  snapshots: [
    {
      id: 'commitment-2019-02-21',
      label: '2025 endpoints publicly committed',
      phase: 'commitment',
      knowledgeCutoff: '2019-02-21',
      factRefs: ['target-stores-2025', 'target-sales-2025', 'digital-sales-us-2018', 'loyalty-users-2018', 'new-store-payback-2018'],
      systems: {
        discernment: { status: 'inferred', confidence: 'medium', summary: 'The commitment named two clear endpoints and tied growth to data-driven decisions, franchisee economics, and operating fundamentals.', factRefs: ['target-stores-2025', 'target-sales-2025', 'new-store-payback-2018'], unknowns: ['Sensitivity range behind the endpoints', 'Conditions for revising the goals'] },
        invention: { status: 'evidenced', confidence: 'medium', summary: 'Digital ordering and a large loyalty base supplied adopted capabilities that could support further growth.', factRefs: ['digital-sales-us-2018', 'loyalty-users-2018'], unknowns: ['Incremental adoption economics by feature and market'] },
        operations: { status: 'evidenced', confidence: 'medium', summary: 'The commitment rested on operational simplicity and sub-three-year average new-store payback.', factRefs: ['new-store-payback-2018'], unknowns: ['Delivery cycle time', 'Store-level dispersion', 'Capacity by market'] },
        execution: { status: 'inferred', confidence: 'medium', summary: 'Existing digital adoption and store economics offered release and adoption evidence, but the seven-year expansion path was not disclosed as staged gates.', factRefs: ['digital-sales-us-2018', 'new-store-payback-2018'], unknowns: ['Annual gate criteria', 'Market exit and pause rules'] },
        advantage: { status: 'evidenced', confidence: 'medium', summary: 'Digital adoption, loyalty participation, and franchisee payback provided multiple forms of externally realized value.', factRefs: ['digital-sales-us-2018', 'loyalty-users-2018', 'new-store-payback-2018'], unknowns: ['Causal lift from each capability', 'Competitor benchmarks'] },
        resource: { status: 'evidenced', confidence: 'medium', summary: 'Reported franchisee payback indicates renewable unit-level capital capacity, though the distribution of returns is not disclosed.', factRefs: ['new-store-payback-2018'], unknowns: ['Payback distribution', 'Corporate and franchise funding limits', 'People capacity'] },
      },
      constraints: {
        people: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The annual report does not quantify store-management, franchisee, delivery, or technology talent capacity against the goal.', factRefs: [], unknowns: ['Critical-role supply', 'Turnover', 'Franchisee pipeline'] },
        finance: { status: 'inferred', confidence: 'medium', summary: 'Sub-three-year average new-store payback supports investment capacity, but does not establish every market can finance the required pace.', factRefs: ['new-store-payback-2018'], unknowns: ['Market-level capital supply', 'Return dispersion', 'Corporate investment envelope'] },
        time: { status: 'evidenced', confidence: 'high', summary: 'Both endpoints have an explicit end-of-2025 deadline.', factRefs: ['target-stores-2025', 'target-sales-2025'], unknowns: ['Annual milestone schedule'] },
        risk: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The commitment does not state tolerance for market-level closures, franchisee stress, cyber exposure, or delivery degradation.', factRefs: [], unknowns: ['Risk limits', 'Quality gates', 'Downside scenarios'] },
      },
    },
    {
      id: 'update-2020-02-20',
      label: 'Owned digital platform operating at global scale',
      phase: 'material-update',
      knowledgeCutoff: '2020-02-20',
      factRefs: ['in-house-ordering-platform', 'global-digital-sales-2019'],
      systems: {
        discernment: { status: 'inferred', confidence: 'low', summary: 'The in-house platform decision was being reinforced by global digital adoption, but the filing does not connect it directly to revised 2025 forecasts.', factRefs: ['in-house-ordering-platform', 'global-digital-sales-2019'], unknowns: ['Updated endpoint forecast', 'Alternative platform analysis'] },
        invention: { status: 'evidenced', confidence: 'high', summary: 'An internally developed ordering platform had achieved adoption across more than half of global retail sales.', factRefs: ['in-house-ordering-platform', 'global-digital-sales-2019'], unknowns: ['Market-level adoption distribution'] },
        operations: { status: 'evidenced', confidence: 'medium', summary: 'Digital ordering had become a major operating channel at global system scale.', factRefs: ['global-digital-sales-2019'], unknowns: ['Order-to-delivery cycle time', 'Reliability and exception rate'] },
        execution: { status: 'evidenced', confidence: 'medium', summary: 'The case shows a repeated capability cycle from the 2010 build decision to broad 2019 adoption.', factRefs: ['in-house-ordering-platform', 'global-digital-sales-2019'], unknowns: ['Release cadence', 'Failure and recovery metrics'] },
        advantage: { status: 'evidenced', confidence: 'medium', summary: 'Domino’s controlled a widely adopted transaction platform rather than relying entirely on external aggregators.', factRefs: ['in-house-ordering-platform', 'global-digital-sales-2019'], unknowns: ['Incremental margin and retention attributable to ownership'] },
        resource: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'Digital scale is visible, but the update does not disclose its cumulative investment or return.', factRefs: ['global-digital-sales-2019'], unknowns: ['Platform investment', 'Operating cost per order', 'Return on technology capital'] },
      },
      constraints: {
        people: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'Technology and store labor capacity remain unquantified.', factRefs: [], unknowns: ['Engineering capacity', 'Store labor load', 'Franchisee readiness'] },
        finance: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'No case-specific capital envelope or constraint threshold is disclosed.', factRefs: [], unknowns: ['Digital investment', 'Expansion funding', 'Return threshold'] },
        time: { status: 'evidenced', confidence: 'medium', summary: 'The case had approximately six years from fiscal 2019 year-end to the endpoint deadline.', factRefs: ['target-stores-2025', 'target-sales-2025', 'global-digital-sales-2019'], unknowns: ['Milestone pace required in each geography'] },
        risk: { status: 'inferred', confidence: 'low', summary: 'Owning the ordering platform increases control while concentrating operational and cyber responsibility inside Domino’s.', factRefs: ['in-house-ordering-platform', 'global-digital-sales-2019'], unknowns: ['Availability, cyber, and recovery metrics'] },
      },
    },
    {
      id: 'outcome-2026-02-23',
      label: 'Endpoints missed amid continued growth',
      phase: 'outcome',
      knowledgeCutoff: '2026-02-23',
      factRefs: [
        'target-stores-2025',
        'target-sales-2025',
        'digital-sales-us-2018',
        'loyalty-users-2018',
        'new-store-payback-2018',
        'in-house-ordering-platform',
        'global-digital-sales-2019',
        'actual-stores-2025',
        'actual-sales-2025',
        'net-store-growth-2025',
        'operating-income-growth-2025',
        'store-target-attainment',
        'sales-target-attainment',
        'store-target-shortfall',
        'sales-target-shortfall',
        'global-retail-sales-per-store-2025',
      ],
      systems: {
        discernment: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The results establish the outcome but do not disclose when management concluded the original endpoints were no longer reachable.', factRefs: ['store-target-attainment', 'sales-target-attainment'], unknowns: ['Forecast revisions', 'Decision dates', 'Goal-retirement criteria'] },
        invention: { status: 'inferred', confidence: 'medium', summary: 'The business continued to add stores and sales, indicating an adopted operating proposition even though the original scale endpoints were missed.', factRefs: ['net-store-growth-2025', 'actual-sales-2025'], unknowns: ['Innovation-specific contribution to 2025 growth'] },
        operations: { status: 'evidenced', confidence: 'high', summary: 'The system added 776 net stores and grew operating income 8.5% during the endpoint year.', factRefs: ['net-store-growth-2025', 'operating-income-growth-2025'], unknowns: ['Store-level service and profitability distribution'] },
        execution: { status: 'evidenced', confidence: 'high', summary: 'Execution produced continued growth but reached 22,142 rather than 25,000 stores and $20.1268 billion rather than more than $25 billion of sales.', factRefs: ['actual-stores-2025', 'actual-sales-2025', 'store-target-attainment', 'sales-target-attainment'], unknowns: ['Milestone-by-milestone variance'] },
        advantage: { status: 'evidenced', confidence: 'medium', summary: 'Positive sales and operating-income growth show continuing economic value; missing the endpoints does not by itself negate that advantage.', factRefs: ['actual-sales-2025', 'operating-income-growth-2025'], unknowns: ['Market-share and unit-economic contribution over the entire case window'] },
        resource: { status: 'evidenced', confidence: 'medium', summary: 'Net store additions and operating-income growth show continuing reinvestment capacity despite the endpoint shortfall.', factRefs: ['net-store-growth-2025', 'operating-income-growth-2025'], unknowns: ['2025 new-store payback', 'Franchisee return distribution', 'Cumulative investment'] },
      },
      constraints: {
        people: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'Outcome disclosures do not identify whether labor, franchisee, or leadership capacity limited the endpoint.', factRefs: [], unknowns: ['Critical-role capacity', 'Franchisee supply', 'Turnover and labor availability'] },
        finance: { status: 'inferred', confidence: 'medium', summary: 'Operating income grew while expansion continued, so the public evidence does not support labeling finance as exhausted.', factRefs: ['net-store-growth-2025', 'operating-income-growth-2025'], unknowns: ['Market-level funding constraints', 'Return dispersion'] },
        time: { status: 'evidenced', confidence: 'high', summary: 'Both explicit endpoint tests were evaluated at the stated end-of-2025 deadline and were not reached.', factRefs: ['store-target-attainment', 'sales-target-attainment'], unknowns: ['Whether management formally extended or replaced the goals before year-end'] },
        risk: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The endpoint result alone does not establish that risk tolerance was binding.', factRefs: [], unknowns: ['Closures and market exits', 'Quality and cyber incidents', 'Franchisee distress'] },
      },
    },
  ],
});
