import { CASE_PROFILE_SCHEMA, defineCaseProfile } from './profile';

export const FORD_MODEL_E = defineCaseProfile({
  schema: CASE_PROFILE_SCHEMA,
  id: 'ford-model-e-2022-2026',
  version: '1.0.0',
  company: { name: 'Ford Motor Company', ticker: 'F', exchange: 'NYSE' },
  case: {
    name: 'Model e electric-vehicle scale and profitability transformation',
    scope: 'Ford Model e and the supporting battery and manufacturing system from the 2022 scale commitment through the latest included fiscal 2024 filing.',
    announcedAt: '2022-03-02',
    status: 'ongoing',
    commitment: 'Scale global EV production capacity to more than two million units annually and reach an 8% Model e EBIT margin by the end of 2026, supported by more than $50 billion of EV investment.',
    targets: [
      {
        id: 'ev-run-rate-2023',
        label: 'Reach a 600,000-unit annual global EV production run rate by late 2023.',
        deadline: '2023-12-31',
        target: { value: 600000, unit: 'annualized EV production units' },
        evidence: [{ sourceId: 'ford-battery-plan-2022', locator: 'News highlights and production plan' }],
      },
      {
        id: 'ev-run-rate-2026',
        label: 'Reach a global EV production run rate of more than two million units annually by the end of 2026.',
        deadline: '2026-12-31',
        target: { value: 2000000, unit: 'annualized EV production units, lower bound' },
        evidence: [{ sourceId: 'ford-battery-plan-2022', locator: 'Driving to more than 2 million EVs by late 2026' }],
      },
      {
        id: 'model-e-margin-2026',
        label: 'Reach an 8% Model e EBIT margin by the end of 2026.',
        deadline: '2026-12-31',
        target: { value: 8, unit: 'percent EBIT margin' },
        evidence: [{ sourceId: 'ford-battery-plan-2022', locator: 'Investment and margin targets' }],
      },
    ],
  },
  scoring: {
    status: 'scored',
    rubricVersion: '0.2.0',
    scorecardId: 'ford-model-e-latest-evidence-2025-v0.2',
    scope: 'latest-evidence-calibration',
    reason: 'The latest-evidence scorecard tests the original commitments against observed milestone re-timing and 2024 economics without claiming the still-open 2026 endpoint is a final outcome.',
  },
  sources: [
    {
      id: 'ford-battery-plan-2022',
      title: 'Ford Releases New Battery Capacity Plan, Raw Materials Details to Scale EVs',
      publisher: 'Ford Motor Company',
      kind: 'company-release',
      publishedAt: '2022-07-21',
      url: 'https://media.ford.com/content/fordmedia/feu/gb/en/news/2022/07/21/Ford-Releases-New-Battery-Capacity-Plan.html',
    },
    {
      id: 'ford-q2-results-2023',
      title: 'Ford Pro, Ford Blue Drive Solid Second-Quarter Results; Company Raises Expectations for Full-Year 2023 Profitability',
      publisher: 'Ford Motor Company',
      kind: 'earnings-release',
      publishedAt: '2023-07-28',
      url: 'https://media.ford.com/content/fordmedia/fap/cn/en/news/2023/07/28/second-quarter-2023-financial-results.html',
    },
    {
      id: 'ford-ev-plan-2024',
      title: 'Ford Updates EV, Hybrid Plans, Readies Manufacturing Plants',
      publisher: 'Ford Motor Company',
      kind: 'company-release',
      publishedAt: '2024-04-04',
      url: 'https://media.ford.com/content/fordmedia/fna/ca/en/news/2024/04/04/ford-updates-timing-for-next-gen-evs--readies-manufacturing-plan.html',
    },
    {
      id: 'ford-2024-10k',
      title: 'Ford Motor Company 2024 Form 10-K',
      publisher: 'U.S. Securities and Exchange Commission',
      kind: 'filing',
      publishedAt: '2025-02-06',
      url: 'https://www.sec.gov/Archives/edgar/data/37996/000003799625000013/f-20241231.htm',
    },
  ],
  facts: [
    {
      id: 'target-run-rate-2023',
      statement: 'Ford targeted a 600,000-unit annual global EV production run rate by late 2023.',
      observedAt: '2022-07-21',
      origin: 'reported',
      metric: { value: 600000, unit: 'annualized EV production units' },
      evidence: [{ sourceId: 'ford-battery-plan-2022', locator: 'News highlights' }],
    },
    {
      id: 'target-run-rate-2026',
      statement: 'Ford targeted a global EV production run rate of more than two million units by the end of 2026.',
      observedAt: '2022-07-21',
      origin: 'reported',
      metric: { value: 2000000, unit: 'annualized EV production units, lower bound' },
      evidence: [{ sourceId: 'ford-battery-plan-2022', locator: 'Driving to more than 2 million EVs by late 2026' }],
    },
    {
      id: 'target-margin-2026',
      statement: 'Ford targeted an 8% EBIT margin for its EV business by the end of 2026.',
      observedAt: '2022-07-21',
      origin: 'reported',
      metric: { value: 8, unit: 'percent EBIT margin' },
      evidence: [{ sourceId: 'ford-battery-plan-2022', locator: 'Investment and margin targets' }],
    },
    {
      id: 'planned-ev-investment',
      statement: 'Ford said it planned to invest more than $50 billion in EVs through 2026.',
      observedAt: '2022-07-21',
      origin: 'reported',
      metric: { value: 50, unit: 'USD billions, lower bound' },
      evidence: [{ sourceId: 'ford-battery-plan-2022', locator: 'Investment and margin targets' }],
    },
    {
      id: 'battery-capacity-sourced-2022',
      statement: 'Ford said it had sourced approximately 70% of the battery-cell capacity needed for the two-million-unit 2026 run-rate target.',
      observedAt: '2022-07-21',
      origin: 'reported',
      metric: { value: 70, unit: 'percent of required battery-cell capacity' },
      evidence: [{ sourceId: 'ford-battery-plan-2022', locator: 'Driving to more than 2 million EVs by late 2026' }],
    },
    {
      id: 'run-rate-retimed-2023',
      statement: 'In July 2023 Ford said it expected to reach the 600,000-unit EV production run rate during 2024 rather than by late 2023.',
      observedAt: '2023-07-28',
      origin: 'reported',
      evidence: [{ sourceId: 'ford-q2-results-2023', locator: 'Ford Model e outlook and production timing' }],
    },
    {
      id: 'oakville-launch-retimed',
      statement: 'Ford re-timed the launch of its three-row electric vehicles at Oakville from 2025 to 2027.',
      observedAt: '2024-04-04',
      origin: 'reported',
      evidence: [{ sourceId: 'ford-ev-plan-2024', locator: 'Assembly plant in Oakville, Ontario' }],
    },
    {
      id: 'model-e-wholesales-2024',
      statement: 'Ford Model e reported 105,000 wholesale units in 2024, down 9% from 2023.',
      observedAt: '2024-12-31',
      origin: 'reported',
      metric: { value: 105000, unit: 'wholesale units' },
      evidence: [{ sourceId: 'ford-2024-10k', locator: 'MD&A, Ford Model e full-year key metrics' }],
    },
    {
      id: 'model-e-revenue-2024',
      statement: 'Ford Model e reported $3.858 billion of 2024 revenue, down 35% from 2023.',
      observedAt: '2024-12-31',
      origin: 'reported',
      metric: { value: 3.858, unit: 'USD billions revenue' },
      evidence: [{ sourceId: 'ford-2024-10k', locator: 'MD&A, Ford Model e full-year key metrics' }],
    },
    {
      id: 'model-e-ebit-2024',
      statement: 'Ford Model e reported a $5.076 billion EBIT loss in 2024.',
      observedAt: '2024-12-31',
      origin: 'reported',
      metric: { value: -5.076, unit: 'USD billions EBIT' },
      evidence: [{ sourceId: 'ford-2024-10k', locator: 'MD&A, Ford Model e full-year EBIT' }],
    },
    {
      id: 'model-e-margin-2024',
      statement: 'Ford Model e reported a negative 131.8% EBIT margin in 2024.',
      observedAt: '2024-12-31',
      origin: 'reported',
      metric: { value: -131.8, unit: 'percent EBIT margin' },
      evidence: [{ sourceId: 'ford-2024-10k', locator: 'MD&A, Ford Model e full-year EBIT' }],
    },
    {
      id: 'model-e-margin-gap-2024',
      statement: 'Ford Model e finished 2024 139.8 percentage points below the stated positive 8% EBIT-margin endpoint.',
      observedAt: '2024-12-31',
      origin: 'derived',
      metric: { value: -139.8, unit: 'percentage points versus 8% EBIT-margin target' },
      calculation: '-131.8% reported 2024 Model e EBIT margin − 8% target margin = -139.8 percentage points.',
      evidence: [
        { sourceId: 'ford-battery-plan-2022', locator: 'Investment and margin targets' },
        { sourceId: 'ford-2024-10k', locator: 'MD&A, Ford Model e full-year EBIT' },
      ],
    },
    {
      id: 'model-e-revenue-per-wholesale-2024',
      statement: 'Model e revenue averaged approximately $36,743 per wholesale unit in 2024 as a segment-scale ratio.',
      observedAt: '2024-12-31',
      origin: 'derived',
      metric: { value: 36742.86, unit: 'USD revenue per wholesale unit' },
      calculation: '$3.858 billion Model e revenue / 105,000 wholesale units = approximately $36,742.86; this is not a vehicle transaction price.',
      evidence: [{ sourceId: 'ford-2024-10k', locator: 'MD&A, Ford Model e full-year revenue and wholesales' }],
    },
    {
      id: 'model-e-ebit-per-wholesale-2024',
      statement: 'Model e EBIT averaged approximately negative $48,343 per wholesale unit in 2024 as a segment-scale ratio.',
      observedAt: '2024-12-31',
      origin: 'derived',
      metric: { value: -48342.86, unit: 'USD EBIT per wholesale unit' },
      calculation: '-$5.076 billion Model e EBIT / 105,000 wholesale units = approximately -$48,342.86; this is not vehicle contribution margin.',
      evidence: [{ sourceId: 'ford-2024-10k', locator: 'MD&A, Ford Model e full-year EBIT and wholesales' }],
    },
    {
      id: 'missed-intermediate-run-rate-milestone',
      statement: 'The original late-2023 600,000-unit EV production run-rate milestone was not achieved by its deadline and was re-timed into 2024.',
      observedAt: '2023-07-28',
      origin: 'derived',
      metric: { value: -1, unit: 'missed dated milestones' },
      calculation: 'One explicitly dated intermediate milestone moved beyond its stated deadline; wholesale volume is not substituted for production run rate.',
      evidence: [
        { sourceId: 'ford-battery-plan-2022', locator: '600,000-unit late-2023 production plan' },
        { sourceId: 'ford-q2-results-2023', locator: 'Ford Model e outlook and production timing' },
      ],
    },
  ],
  snapshots: [
    {
      id: 'commitment-2022-07-21',
      label: 'EV scale and margin targets supported by a battery plan',
      phase: 'commitment',
      knowledgeCutoff: '2022-07-21',
      factRefs: ['target-run-rate-2023', 'target-run-rate-2026', 'target-margin-2026', 'planned-ev-investment', 'battery-capacity-sourced-2022'],
      systems: {
        discernment: { status: 'evidenced', confidence: 'medium', summary: 'Ford published specific scale, margin, investment, and supply assumptions, making the thesis inspectable.', factRefs: ['target-run-rate-2023', 'target-run-rate-2026', 'target-margin-2026', 'battery-capacity-sourced-2022'], unknowns: ['Demand downside', 'Thresholds for re-timing', 'Alternative portfolio cases'] },
        invention: { status: 'inferred', confidence: 'medium', summary: 'The commitment joined new EV products, battery chemistries, supply partnerships, and manufacturing capacity.', factRefs: ['target-run-rate-2026', 'battery-capacity-sourced-2022'], unknowns: ['Vehicle-level adoption and contribution margin', 'Technology maturity by program'] },
        operations: { status: 'inferred', confidence: 'medium', summary: 'The plan required a large industrial conversion across plants, battery supply, materials, and vehicle programs.', factRefs: ['target-run-rate-2023', 'battery-capacity-sourced-2022'], unknowns: ['Plant ramp curves', 'Yield', 'Supplier cycle times', 'Quality capacity'] },
        execution: { status: 'inferred', confidence: 'low', summary: 'Milestones were explicit, but the release did not disclose the complete assurance, launch-gate, and ramp criteria.', factRefs: ['target-run-rate-2023', 'target-run-rate-2026'], unknowns: ['Launch gates', 'Quality thresholds', 'Reversible capacity steps'] },
        advantage: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'Demand enthusiasm and supply contracts supported the thesis, but profitable external value had not yet been demonstrated at target scale.', factRefs: ['target-margin-2026'], unknowns: ['Sustainable pricing', 'Customer adoption', 'Unit contribution margin'] },
        resource: { status: 'evidenced', confidence: 'medium', summary: 'More than $50 billion of planned investment made the resource commitment explicit before the target margin was realized.', factRefs: ['planned-ev-investment', 'target-margin-2026'], unknowns: ['Annual funding peak', 'Return thresholds', 'Capital reallocation rules'] },
      },
      constraints: {
        people: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The plan did not quantify critical engineering, software, battery, manufacturing, or skilled-trades capacity.', factRefs: [], unknowns: ['Critical-role supply', 'Hiring and training lead time', 'Organizational load'] },
        finance: { status: 'evidenced', confidence: 'medium', summary: 'The investment scale and future margin target show substantial capital consumption before economic proof.', factRefs: ['planned-ev-investment', 'target-margin-2026'], unknowns: ['Cash-flow trough', 'Maximum acceptable loss', 'Program-level returns'] },
        time: { status: 'evidenced', confidence: 'high', summary: 'The plan contained a late-2023 intermediate run-rate milestone and end-2026 scale and margin endpoints.', factRefs: ['target-run-rate-2023', 'target-run-rate-2026', 'target-margin-2026'], unknowns: ['Schedule reserve', 'Critical-path lead times'] },
        risk: { status: 'inferred', confidence: 'medium', summary: 'Only 70% of required 2026 battery capacity was sourced, leaving execution, demand, technology, commodity, and partner exposure.', factRefs: ['battery-capacity-sourced-2022'], unknowns: ['Contract firmness', 'Quality gates', 'Downside-demand scenario', 'Exit costs'] },
      },
    },
    {
      id: 'update-2024-04-04',
      label: 'Production and product milestones re-timed',
      phase: 'material-update',
      knowledgeCutoff: '2024-04-04',
      factRefs: ['run-rate-retimed-2023', 'oakville-launch-retimed'],
      systems: {
        discernment: { status: 'evidenced', confidence: 'medium', summary: 'Ford incorporated demand and technology timing into revised production and product-launch decisions.', factRefs: ['run-rate-retimed-2023', 'oakville-launch-retimed'], unknowns: ['Updated 2026 probability and target status', 'Board thresholds'] },
        invention: { status: 'inferred', confidence: 'medium', summary: 'The Oakville delay was intended to allow the market and emerging battery technology to develop before release.', factRefs: ['oakville-launch-retimed'], unknowns: ['Revised product economics', 'Technology-readiness evidence'] },
        operations: { status: 'evidenced', confidence: 'medium', summary: 'The production run-rate milestone and a major plant-supported launch moved later, showing industrial timing constraints.', factRefs: ['run-rate-retimed-2023', 'oakville-launch-retimed'], unknowns: ['Plant utilization impact', 'Supplier and labor consequences'] },
        execution: { status: 'evidenced', confidence: 'medium', summary: 'Ford chose to re-time rather than force the original release calendar, preserving a bounded adjustment option.', factRefs: ['oakville-launch-retimed'], unknowns: ['Assurance criteria', 'Cost of delay', 'Other program gate changes'] },
        advantage: { status: 'inferred', confidence: 'low', summary: 'The update prioritized profitable growth and customer value over the original product timing, but did not yet prove the revised economics.', factRefs: ['oakville-launch-retimed'], unknowns: ['Demand elasticity', 'Competitive position', 'Revised unit economics'] },
        resource: { status: 'inferred', confidence: 'medium', summary: 'Re-timing changed when committed facilities and teams could generate return.', factRefs: ['oakville-launch-retimed'], unknowns: ['Idle and conversion cost', 'Capital reallocation', 'Updated payback'] },
      },
      constraints: {
        people: { status: 'inferred', confidence: 'low', summary: 'Ford acknowledged workforce impact at Oakville, but did not quantify capacity utilization or redeployment.', factRefs: ['oakville-launch-retimed'], unknowns: ['Affected headcount', 'Redeployment plan', 'Skill retention'] },
        finance: { status: 'inferred', confidence: 'medium', summary: 'Delayed launches postpone return on already committed plant and product investment.', factRefs: ['oakville-launch-retimed', 'planned-ev-investment'], unknowns: ['Delay cost', 'Revised cash flow', 'Impairment exposure'] },
        time: { status: 'evidenced', confidence: 'high', summary: 'The 600,000-unit run-rate milestone moved into 2024 and the Oakville launch moved from 2025 to 2027.', factRefs: ['run-rate-retimed-2023', 'oakville-launch-retimed'], unknowns: ['Status of the end-2026 production and margin endpoints'] },
        risk: { status: 'evidenced', confidence: 'medium', summary: 'Re-timing reduced immediate launch exposure while creating delay, capital, workforce, and competitive risks.', factRefs: ['oakville-launch-retimed'], unknowns: ['Net risk comparison', 'Cancellation thresholds', 'Recoverability of committed assets'] },
      },
    },
    {
      id: 'ongoing-2025-02-06',
      label: 'Fiscal 2024 economic and volume evidence',
      phase: 'ongoing',
      knowledgeCutoff: '2025-02-06',
      factRefs: [
        'target-run-rate-2023',
        'target-run-rate-2026',
        'target-margin-2026',
        'planned-ev-investment',
        'battery-capacity-sourced-2022',
        'run-rate-retimed-2023',
        'oakville-launch-retimed',
        'model-e-wholesales-2024',
        'model-e-revenue-2024',
        'model-e-ebit-2024',
        'model-e-margin-2024',
        'model-e-margin-gap-2024',
        'model-e-revenue-per-wholesale-2024',
        'model-e-ebit-per-wholesale-2024',
        'missed-intermediate-run-rate-milestone',
      ],
      systems: {
        discernment: { status: 'inferred', confidence: 'medium', summary: 'The combination of re-timed milestones, lower volume, lower revenue, and large losses supplied strong evidence for further portfolio adjustment.', factRefs: ['run-rate-retimed-2023', 'model-e-revenue-2024', 'model-e-ebit-2024'], unknowns: ['Formal status of the original 2026 targets', 'Decision alternatives'] },
        invention: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'Segment totals do not identify which product or technology configurations were gaining durable adoption.', factRefs: ['model-e-wholesales-2024'], unknowns: ['Model-level demand', 'Battery and platform economics', 'Repeat adoption'] },
        operations: { status: 'evidenced', confidence: 'medium', summary: 'Wholesale volume fell 9% and revenue fell 35%, showing that available industrial capacity was not translating into the planned scale economics.', factRefs: ['model-e-wholesales-2024', 'model-e-revenue-2024'], unknowns: ['Production run rate', 'Capacity utilization', 'Inventory and yield'] },
        execution: { status: 'evidenced', confidence: 'medium', summary: 'The case contains commitment, milestone re-timing, product re-timing, and operating outcomes, but the end-2026 endpoint is not yet observable.', factRefs: ['target-run-rate-2026', 'run-rate-retimed-2023', 'oakville-launch-retimed', 'model-e-wholesales-2024'], unknowns: ['2026 endpoint outcome', 'Gate-level quality and adoption data'] },
        advantage: { status: 'evidenced', confidence: 'high', summary: 'A negative 131.8% segment EBIT margin is direct evidence that Model e had not established profitable economic advantage in 2024.', factRefs: ['model-e-margin-2024', 'model-e-ebit-2024'], unknowns: ['Lifetime customer value', 'Future-platform economics', 'Portfolio spillovers'] },
        resource: { status: 'evidenced', confidence: 'high', summary: 'A $5.076 billion annual EBIT loss against a large multiyear investment program makes finance a material observed constraint.', factRefs: ['planned-ev-investment', 'model-e-ebit-2024'], unknowns: ['Cumulative program investment', 'Cash versus accounting loss', 'Future capital commitments'] },
      },
      constraints: {
        people: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The filing does not provide case-specific critical-role capacity or workload.', factRefs: [], unknowns: ['Engineering and manufacturing capacity', 'Turnover', 'Redeployment after re-timing'] },
        finance: { status: 'evidenced', confidence: 'high', summary: 'The segment loss and negative margin demonstrate heavy financial consumption far from the stated positive-margin endpoint.', factRefs: ['model-e-ebit-2024', 'model-e-margin-2024'], unknowns: ['Maximum tolerable future loss', 'Program-level capital recoverability'] },
        time: { status: 'evidenced', confidence: 'high', summary: 'Material milestones had already moved while the end-2026 targets approached.', factRefs: ['run-rate-retimed-2023', 'oakville-launch-retimed', 'target-run-rate-2026', 'target-margin-2026'], unknowns: ['Current official endpoint forecast'] },
        risk: { status: 'inferred', confidence: 'medium', summary: 'Lower pricing and volumes, delayed products, and committed investment create material demand, competitive, and capital-recovery exposure.', factRefs: ['oakville-launch-retimed', 'model-e-revenue-2024', 'model-e-ebit-2024'], unknowns: ['Risk limits', 'Asset impairment by program', 'Quality and warranty exposure'] },
      },
    },
  ],
});
