import type { CaseFact, CaseProfile, CaseSource } from './profile';

/**
 * Renders the case library's evidence sheet.
 *
 * Kept beside the profiles rather than inside the build script so the drift
 * test can call the same function the generator calls. A test that reimplements
 * the format checks that two copies agree, not that the file is current.
 */

const KIND_LABEL: Record<CaseSource['kind'], string> = {
  filing: 'Regulatory filing',
  'annual-report': 'Annual report',
  'earnings-release': 'Earnings release',
  'company-release': 'Company release',
  'audit-report': 'Audit report',
  'agency-release': 'Agency release',
  news: 'News report',
};

/** Facts resting on a source, in the order the profile declares them. */
function factsCiting(profile: CaseProfile, sourceId: string): readonly CaseFact[] {
  return profile.facts.filter((fact) => fact.evidence.some((ref) => ref.sourceId === sourceId));
}

function metricText(fact: CaseFact): string {
  const { metric } = fact;
  if (!metric) return '—';
  const n = (value: number) => value.toLocaleString('en-US', { maximumFractionDigits: 4 });
  return 'value' in metric
    ? `${n(metric.value)} ${metric.unit}`
    : `${n(metric.low)}–${n(metric.high)} ${metric.unit}`;
}

/** Markdown table cells cannot carry a raw pipe or a line break. */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}

export function renderCaseSources(profiles: readonly CaseProfile[]): string {
  const lines: string[] = [
    '<!-- Generated by scripts/gen-case-sources.ts. Do not edit by hand. -->',
    '',
    '# StratOS case evidence sources',
    '',
    'Every document the case library rests on, with the facts each one carries.',
    'A verdict cites facts; a fact cites a source; a source is listed here with the',
    'date a public analyst could first use it. That date is what the knowledge',
    'cutoffs enforce, so it is the column that decides which evidence a scored',
    'decision is allowed to see.',
    '',
    '`Reported` facts reproduce a figure the document states. `Derived` facts are',
    'computed from reported ones and carry their calculation in the profile.',
    '',
  ];

  const totalSources = profiles.reduce((n, p) => n + p.sources.length, 0);
  const totalFacts = profiles.reduce((n, p) => n + p.facts.length, 0);
  lines.push(
    `**${profiles.length} cases · ${totalSources} sources · ${totalFacts} facts**`,
    '',
    '| Case | Sources | Facts | Evidence spans |',
    '| --- | ---: | ---: | --- |',
  );
  for (const profile of profiles) {
    const dates = profile.sources.map(({ publishedAt }) => publishedAt).sort();
    lines.push(
      `| [${cell(profile.company.name)}](#${profile.id}) | ${profile.sources.length} | `
      + `${profile.facts.length} | ${dates[0]} → ${dates[dates.length - 1]} |`,
    );
  }
  lines.push('');

  for (const profile of profiles) {
    const { company } = profile;
    const ticker = company.ticker ? ` (${company.exchange ?? ''}: ${company.ticker})`.replace('(: ', '(') : '';
    lines.push('---', '', `## ${company.name}${ticker}`, '', `\`${profile.id}\``, '');

    const ordered = [...profile.sources].sort((a, b) => a.publishedAt.localeCompare(b.publishedAt));
    for (const source of ordered) {
      const cited = factsCiting(profile, source.id);
      lines.push(
        `### ${source.publishedAt} · ${source.title}`,
        '',
        `- **Publisher** — ${source.publisher}`,
        `- **Kind** — ${KIND_LABEL[source.kind]}`,
        `- **Reference** — \`${source.id}\``,
        `- **URL** — <${source.url}>`,
        '',
      );
      if (cited.length === 0) {
        lines.push('No fact currently cites this source.', '');
        continue;
      }
      lines.push(
        '| Fact | Observed | Origin | Metric |',
        '| --- | --- | --- | --- |',
        ...cited.map((fact) => (
          `| \`${fact.id}\` — ${cell(fact.statement)} | ${fact.observedAt} `
          + `| ${fact.origin === 'reported' ? 'Reported' : 'Derived'} | ${cell(metricText(fact))} |`
        )),
        '',
      );
    }
  }

  return `${lines.join('\n').trimEnd()}\n`;
}
