import { CASE_PROFILE_SCHEMA, defineCaseProfile } from './profile';

export const TARGET_CANADA = defineCaseProfile({
  schema: CASE_PROFILE_SCHEMA,
  id: 'target-canada-2012-2015',
  version: '1.0.0',
  company: { name: 'Target Corporation', ticker: 'TGT', exchange: 'NYSE' },
  case: {
    name: 'Canada market entry',
    scope: 'Target Corporation retail operations in Canada from the announced 2013 store program through the 2015 exit decision.',
    announcedAt: '2012-07-12',
    status: 'completed',
    commitment: 'Open 125 to 135 Target stores in Canada beginning in March or April 2013, with the first 125 planned during 2013.',
    targets: [
      {
        id: 'canada-store-program',
        label: 'Open the first 125 Canadian stores during 2013.',
        deadline: '2013-12-31',
        target: { value: 125, unit: 'stores' },
        evidence: [{ sourceId: 'target-store-plan-2012', locator: 'Opening plan, paragraphs 1–2' }],
      },
    ],
  },
  scoring: {
    status: 'scored',
    rubricVersion: '0.2.0',
    scorecardId: 'target-canada-outcome-retrodiction-2015-v0.2',
    scope: 'outcome-calibrated-retrodiction',
    reason: 'Outcome facts backcast realistic people, time, finance, and exposure bounds while preserving their observed, derived, or estimated status.',
  },
  sources: [
    {
      id: 'target-store-plan-2012',
      title: 'Target Confirms Store Locations Opening in 2013',
      publisher: 'Target Corporation',
      kind: 'company-release',
      publishedAt: '2012-07-12',
      url: 'https://corporate.target.com/press/release/2012/07/target-confirms-store-locations-opening-in-2013',
    },
    {
      id: 'target-results-2013',
      title: 'Target Reports Fourth Quarter and Full-Year 2013 Earnings',
      publisher: 'Target Corporation',
      kind: 'earnings-release',
      publishedAt: '2014-02-26',
      url: 'https://corporate.target.com/press/release/2014/02/target-reports-fourth-quarter-and-full-year-2013-earnings',
    },
    {
      id: 'target-exit-2015',
      title: 'Target Corporation Announces Plans to Discontinue Canadian Operations',
      publisher: 'Target Corporation',
      kind: 'company-release',
      publishedAt: '2015-01-15',
      url: 'https://corporate.target.com/press/release/2015/01/target-corporation-announces-plans-to-discontinue-canadian-operations',
    },
    {
      id: 'target-results-2014',
      title: 'Target Reports Fourth Quarter and Full-Year 2014 Earnings',
      publisher: 'Target Corporation',
      kind: 'earnings-release',
      publishedAt: '2015-02-25',
      url: 'https://corporate.target.com/press/release/2015/02/target-reports-fourth-quarter-and-full-year-2014-earnings',
    },
  ],
  facts: [
    {
      id: 'planned-stores-2013',
      statement: 'Target confirmed the first 125 Canadian stores and planned to open them during 2013.',
      observedAt: '2012-07-12',
      origin: 'reported',
      metric: { value: 125, unit: 'stores' },
      evidence: [{ sourceId: 'target-store-plan-2012', locator: 'Opening plan, paragraphs 1–2' }],
    },
    {
      id: 'planned-opening-window-months',
      statement: 'Opening 125 stores from March or April through December 2013 implied a nine-to-ten-month physical rollout window.',
      observedAt: '2012-07-12',
      origin: 'derived',
      metric: { low: 9, high: 10, unit: 'months' },
      calculation: 'March through December is 10 calendar months; April through December is 9 calendar months.',
      evidence: [{ sourceId: 'target-store-plan-2012', locator: 'Opening plan, paragraphs 1–2' }],
    },
    {
      id: 'required-store-opening-rate',
      statement: 'The commitment required an average physical opening rate of approximately 12.5 to 13.9 stores per month during the stated window.',
      observedAt: '2012-07-12',
      origin: 'derived',
      metric: { low: 12.5, high: 13.8889, unit: 'stores per month' },
      calculation: '125 stores / 10 months = 12.5; 125 stores / 9 months = 13.8889.',
      evidence: [{ sourceId: 'target-store-plan-2012', locator: 'Opening plan, paragraphs 1–2' }],
    },
    {
      id: 'canada-sales-2013',
      statement: 'The Canadian segment generated approximately $1.3 billion of sales in fiscal 2013.',
      observedAt: '2014-02-01',
      origin: 'reported',
      metric: { value: 1.317, unit: 'USD billions' },
      evidence: [{ sourceId: 'target-results-2013', locator: 'Canadian Segment Results' }],
    },
    {
      id: 'canada-gross-margin-2013',
      statement: 'The Canadian segment reported a 14.9% gross margin rate for fiscal 2013.',
      observedAt: '2014-02-01',
      origin: 'reported',
      metric: { value: 14.9, unit: 'percent' },
      evidence: [{ sourceId: 'target-results-2013', locator: 'Canadian Segment Results' }],
    },
    {
      id: 'canada-ebit-2013',
      statement: 'The Canadian segment reported an EBIT loss of $941 million for fiscal 2013.',
      observedAt: '2014-02-01',
      origin: 'reported',
      metric: { value: -941, unit: 'USD millions EBIT' },
      evidence: [{ sourceId: 'target-results-2013', locator: 'Canadian Segment Results' }],
    },
    {
      id: 'canada-q4-margin-2013',
      statement: 'Fourth-quarter Canadian gross margin was 4.4%, which Target attributed to continued clearance of excess inventory.',
      observedAt: '2014-02-01',
      origin: 'reported',
      metric: { value: 4.4, unit: 'percent' },
      evidence: [{ sourceId: 'target-results-2013', locator: 'Canadian Segment Results, fourth-quarter discussion' }],
    },
    {
      id: 'stores-at-exit',
      statement: 'Target Canada operated 133 stores when the exit was announced.',
      observedAt: '2015-01-15',
      origin: 'reported',
      metric: { value: 133, unit: 'stores' },
      evidence: [{ sourceId: 'target-exit-2015', locator: 'Canada operations summary' }],
    },
    {
      id: 'employees-at-exit',
      statement: 'Target Canada employed approximately 17,600 people when the exit was announced.',
      observedAt: '2015-01-15',
      origin: 'reported',
      metric: { value: 17600, unit: 'employees' },
      evidence: [{ sourceId: 'target-exit-2015', locator: 'Canada operations summary' }],
    },
    {
      id: 'board-approved-exit',
      statement: 'The board approved discontinuing Canadian operations on January 14, 2015.',
      observedAt: '2015-01-14',
      origin: 'reported',
      evidence: [{ sourceId: 'target-results-2014', locator: 'Discontinued Operations' }],
    },
    {
      id: 'exit-charge-2014',
      statement: 'Target recorded $5.105 billion of pretax impairment and other exit charges in the fourth quarter of 2014.',
      observedAt: '2015-01-31',
      origin: 'reported',
      metric: { value: 5.105, unit: 'USD billions pretax charges' },
      evidence: [{ sourceId: 'target-results-2014', locator: 'Discontinued Operations' }],
    },
    {
      id: 'employees-per-store-at-exit',
      statement: 'The exit footprint represented approximately 132.3 employees per store.',
      observedAt: '2015-01-15',
      origin: 'derived',
      metric: { value: 132.3308, unit: 'employees per store' },
      calculation: '17,600 employees / 133 stores = 132.3308 employees per store.',
      evidence: [
        { sourceId: 'target-exit-2015', locator: 'Canada operations summary, store count' },
        { sourceId: 'target-exit-2015', locator: 'Canada operations summary, employee count' },
      ],
    },
    {
      id: 'workforce-equivalent-125-stores',
      statement: 'Applying the exit staffing ratio to the committed 125-store footprint implies approximately 16,541 employees.',
      observedAt: '2015-01-15',
      origin: 'derived',
      metric: { value: 16541.35, unit: 'employees' },
      calculation: '(17,600 employees / 133 stores) × 125 stores = 16,541.35 employees.',
      evidence: [
        { sourceId: 'target-store-plan-2012', locator: 'Opening plan, first 125 stores' },
        { sourceId: 'target-exit-2015', locator: 'Canada operations summary' },
      ],
    },
    {
      id: 'estimated-people-load-range',
      statement: 'A rounded outcome-calibrated people-load range for a 125-store footprint is 15,000 to 18,000 employees.',
      observedAt: '2015-01-15',
      origin: 'derived',
      metric: { low: 15000, high: 18000, unit: 'employees' },
      calculation: 'The 16,541-employee scaled estimate is rounded outward to a 15,000–18,000 range to avoid false precision and allow staffing mix variation.',
      evidence: [
        { sourceId: 'target-store-plan-2012', locator: 'Opening plan, first 125 stores' },
        { sourceId: 'target-exit-2015', locator: 'Canada operations summary' },
      ],
    },
    {
      id: 'gross-profit-2013',
      statement: 'Applying the reported 14.9% gross margin to $1.317 billion of sales implies approximately $196.2 million of gross profit.',
      observedAt: '2014-02-01',
      origin: 'derived',
      metric: { value: 196.233, unit: 'USD millions gross profit' },
      calculation: '$1.317 billion sales × 14.9% gross margin = $196.233 million gross profit.',
      evidence: [
        { sourceId: 'target-results-2013', locator: 'Canadian Segment Results, sales' },
        { sourceId: 'target-results-2013', locator: 'Canadian Segment Results, gross margin' },
      ],
    },
    {
      id: 'ebit-loss-share-of-sales',
      statement: 'The $941 million EBIT loss was approximately 71.5% of Canadian segment sales.',
      observedAt: '2014-02-01',
      origin: 'derived',
      metric: { value: -71.4503, unit: 'percent EBIT margin proxy' },
      calculation: '-$941 million EBIT / $1.317 billion sales × 100 = -71.4503%.',
      evidence: [
        { sourceId: 'target-results-2013', locator: 'Canadian Segment Results, sales' },
        { sourceId: 'target-results-2013', locator: 'Canadian Segment Results, EBIT' },
      ],
    },
    {
      id: 'sales-per-planned-store',
      statement: 'Using the planned 125-store denominator as a scale proxy implies approximately $10.536 million of sales per planned store.',
      observedAt: '2014-02-01',
      origin: 'derived',
      metric: { value: 10.536, unit: 'USD millions sales per planned store' },
      calculation: '$1.317 billion sales / 125 planned stores = $10.536 million; this is a planning-equivalent proxy, not a same-date mature-store metric.',
      evidence: [
        { sourceId: 'target-store-plan-2012', locator: 'Opening plan, first 125 stores' },
        { sourceId: 'target-results-2013', locator: 'Canadian Segment Results, sales' },
      ],
    },
    {
      id: 'gross-profit-per-planned-store',
      statement: 'Using the planned 125-store denominator implies approximately $1.570 million of gross profit per planned store.',
      observedAt: '2014-02-01',
      origin: 'derived',
      metric: { value: 1.5699, unit: 'USD millions gross profit per planned store' },
      calculation: '$196.233 million derived gross profit / 125 planned stores = $1.5699 million.',
      evidence: [
        { sourceId: 'target-store-plan-2012', locator: 'Opening plan, first 125 stores' },
        { sourceId: 'target-results-2013', locator: 'Canadian Segment Results, sales and gross margin' },
      ],
    },
    {
      id: 'ebit-loss-per-planned-store',
      statement: 'Using the planned 125-store denominator implies approximately $7.528 million of EBIT loss per planned store.',
      observedAt: '2014-02-01',
      origin: 'derived',
      metric: { value: -7.528, unit: 'USD millions EBIT per planned store' },
      calculation: '-$941 million EBIT / 125 planned stores = -$7.528 million.',
      evidence: [
        { sourceId: 'target-store-plan-2012', locator: 'Opening plan, first 125 stores' },
        { sourceId: 'target-results-2013', locator: 'Canadian Segment Results, EBIT' },
      ],
    },
    {
      id: 'exit-charge-per-store',
      statement: 'The $5.105 billion exit charge represented approximately $38.38 million per store in the 133-store exit footprint.',
      observedAt: '2015-01-31',
      origin: 'derived',
      metric: { value: 38.3835, unit: 'USD millions exit charge per store' },
      calculation: '$5.105 billion exit charges / 133 stores = $38.3835 million per store.',
      evidence: [
        { sourceId: 'target-exit-2015', locator: 'Canada operations summary, store count' },
        { sourceId: 'target-results-2014', locator: 'Discontinued Operations, exit charges' },
      ],
    },
    {
      id: 'operating-learning-window',
      statement: 'The period from the first March or April 2013 openings to the January 2015 exit decision was approximately 21 to 22 months without establishing a continuing operation.',
      observedAt: '2015-01-14',
      origin: 'derived',
      metric: { low: 21, high: 22, unit: 'months, lower-bound learning window' },
      calculation: 'March 2013 to January 2015 is approximately 22 months; April 2013 to January 2015 is approximately 21 months.',
      evidence: [
        { sourceId: 'target-store-plan-2012', locator: 'Opening plan, March or April 2013 start' },
        { sourceId: 'target-results-2014', locator: 'Discontinued Operations, January 14 2015 board decision' },
      ],
    },
    {
      id: 'operational-time-fit-upper-bound',
      statement: 'Comparing at most ten months in the mass-rollout window with more than 21 months without stable continuing operations places operational time fit below negative 11 months.',
      observedAt: '2015-01-14',
      origin: 'derived',
      metric: { value: -11, unit: 'months, strict upper bound' },
      calculation: 'At most 10 months available − more than 21 months required = fit strictly below -11 months.',
      evidence: [
        { sourceId: 'target-store-plan-2012', locator: 'Opening plan, March or April through December 2013' },
        { sourceId: 'target-results-2014', locator: 'Discontinued Operations, January 14 2015 board decision' },
      ],
    },
  ],
  snapshots: [
    {
      id: 'commitment-2012-07-12',
      label: 'Store program committed',
      phase: 'commitment',
      knowledgeCutoff: '2012-07-12',
      factRefs: ['planned-stores-2013'],
      systems: {
        discernment: { status: 'inferred', confidence: 'low', summary: 'The public commitment specifies scale and timing, but not the disconfirming evidence considered before committing.', factRefs: ['planned-stores-2013'], unknowns: ['Board decision record', 'Test-market evidence', 'Alternatives considered'] },
        invention: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The announcement does not show how the Canadian customer proposition differed from the U.S. model.', factRefs: [], unknowns: ['Localized assortment design', 'Customer research', 'Offering adoption tests'] },
        operations: { status: 'inferred', confidence: 'medium', summary: 'Opening 125 stores within one calendar year implies a large, tightly coupled conversion and supply-chain program.', factRefs: ['planned-stores-2013'], unknowns: ['Distribution readiness', 'Inventory-system readiness', 'Store-opening sequence and throughput'] },
        execution: { status: 'inferred', confidence: 'low', summary: 'A dated launch program is visible, but public evidence does not identify release gates, reversibility, or pilot criteria.', factRefs: ['planned-stores-2013'], unknowns: ['Pilot gates', 'Rollback conditions', 'Assurance results'] },
        advantage: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The commitment states footprint, not the capability or economics expected to create Canadian customer value.', factRefs: [], unknowns: ['Differentiated value proposition', 'Expected market share', 'Target unit economics'] },
        resource: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The release does not disclose the full capital, staffing, or cash-flow envelope for the opening program.', factRefs: [], unknowns: ['Authorized capital', 'Operating-loss tolerance', 'Staffing buffer'] },
      },
      constraints: {
        people: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'No critical-role or staffing-capacity evidence is disclosed.', factRefs: [], unknowns: ['Critical roles', 'Hiring plan', 'Training capacity'] },
        finance: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The announcement does not disclose the investment envelope or loss tolerance.', factRefs: [], unknowns: ['Committed capital', 'Working capital', 'Loss and payback thresholds'] },
        time: { status: 'evidenced', confidence: 'high', summary: 'The first 125 stores were assigned to the 2013 opening window.', factRefs: ['planned-stores-2013'], unknowns: ['Internal milestone slack'] },
        risk: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'Public launch evidence does not describe staged exposure or reversal thresholds.', factRefs: [], unknowns: ['Stage gates', 'Maximum exposure', 'Exit or pause criteria'] },
      },
    },
    {
      id: 'warning-2014-02-26',
      label: 'First full-year operating evidence',
      phase: 'material-update',
      knowledgeCutoff: '2014-02-26',
      factRefs: ['planned-stores-2013', 'canada-sales-2013', 'canada-gross-margin-2013', 'canada-ebit-2013', 'canada-q4-margin-2013'],
      systems: {
        discernment: { status: 'inferred', confidence: 'medium', summary: 'The first full-year results supplied strong contrary economic evidence, but the public record used here does not show the decision process it triggered.', factRefs: ['canada-ebit-2013', 'canada-q4-margin-2013'], unknowns: ['Board response', 'Revised thesis', 'Decision thresholds'] },
        invention: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'Reported financial results do not isolate proposition changes or customer learning.', factRefs: ['canada-sales-2013'], unknowns: ['Adoption by offering', 'Localized proposition changes', 'Repeat behavior'] },
        operations: { status: 'evidenced', confidence: 'high', summary: 'Sales, margin, and excess-inventory clearance show that store flow had not produced sustainable retail economics.', factRefs: ['canada-sales-2013', 'canada-gross-margin-2013', 'canada-q4-margin-2013'], unknowns: ['In-stock rate', 'Distribution cycle time', 'Inventory accuracy'] },
        execution: { status: 'inferred', confidence: 'medium', summary: 'The stores were released at scale, while the resulting margin and inventory evidence indicate that release success cannot be inferred from opening count alone.', factRefs: ['planned-stores-2013', 'canada-q4-margin-2013'], unknowns: ['Pilot results', 'Release gate exceptions', 'Corrective-action cadence'] },
        advantage: { status: 'evidenced', confidence: 'medium', summary: 'The disclosed sales and gross margin did not yet demonstrate durable Canadian segment economics.', factRefs: ['canada-sales-2013', 'canada-gross-margin-2013', 'canada-ebit-2013'], unknowns: ['Customer retention', 'Market share', 'Mature-store economics'] },
        resource: { status: 'evidenced', confidence: 'high', summary: 'A $941 million segment EBIT loss made the resource draw material and directly observable.', factRefs: ['canada-ebit-2013'], unknowns: ['Remaining investment authorization', 'Cash break-even plan', 'People-capacity depletion'] },
      },
      constraints: {
        people: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The selected public evidence still does not quantify staffing load or skill coverage.', factRefs: [], unknowns: ['Turnover', 'Vacancy and training time', 'Management span'] },
        finance: { status: 'evidenced', confidence: 'high', summary: 'The segment EBIT loss establishes substantial financial consumption before economic proof.', factRefs: ['canada-ebit-2013'], unknowns: ['Board loss tolerance', 'Funding runway', 'Incremental recovery investment'] },
        time: { status: 'inferred', confidence: 'medium', summary: 'The store-count program moved faster than the available evidence of stable operating economics.', factRefs: ['planned-stores-2013', 'canada-q4-margin-2013'], unknowns: ['Internal schedule variance', 'Time allowed for corrective cycles'] },
        risk: { status: 'inferred', confidence: 'medium', summary: 'Excess-inventory clearance and segment losses show realized exposure, but predetermined risk limits are not public.', factRefs: ['canada-q4-margin-2013', 'canada-ebit-2013'], unknowns: ['Risk appetite', 'Stop-loss threshold', 'Lease and exit exposure'] },
      },
    },
    {
      id: 'outcome-2015-02-25',
      label: 'Exit and loss recognition',
      phase: 'outcome',
      knowledgeCutoff: '2015-02-25',
      factRefs: [
        'planned-stores-2013',
        'planned-opening-window-months',
        'required-store-opening-rate',
        'canada-sales-2013',
        'canada-gross-margin-2013',
        'canada-ebit-2013',
        'canada-q4-margin-2013',
        'stores-at-exit',
        'employees-at-exit',
        'board-approved-exit',
        'exit-charge-2014',
        'employees-per-store-at-exit',
        'workforce-equivalent-125-stores',
        'estimated-people-load-range',
        'gross-profit-2013',
        'ebit-loss-share-of-sales',
        'sales-per-planned-store',
        'gross-profit-per-planned-store',
        'ebit-loss-per-planned-store',
        'exit-charge-per-store',
        'operating-learning-window',
        'operational-time-fit-upper-bound',
      ],
      systems: {
        discernment: { status: 'evidenced', confidence: 'medium', summary: 'The board ultimately revised the commitment and approved an exit after assessing the Canadian operation.', factRefs: ['board-approved-exit'], unknowns: ['Decision alternatives and weights', 'Exact board thresholds'] },
        invention: { status: 'insufficient-evidence', confidence: 'not-assessed', summary: 'The exit evidence does not isolate which proposition experiments were attempted or learned from.', factRefs: [], unknowns: ['Offering experiments', 'Codified learning', 'Customer-level response'] },
        operations: { status: 'evidenced', confidence: 'high', summary: 'The operating footprint reached 133 stores but did not become a continuing operation.', factRefs: ['stores-at-exit', 'board-approved-exit'], unknowns: ['Store-level dispersion', 'Final service and inventory metrics'] },
        execution: { status: 'evidenced', confidence: 'medium', summary: 'The program achieved physical rollout, but the later exit demonstrates that rollout was not equivalent to validated adoption or sustainable operation.', factRefs: ['stores-at-exit', 'board-approved-exit'], unknowns: ['Release-gate history', 'Timing of corrective interventions'] },
        advantage: { status: 'evidenced', confidence: 'high', summary: 'Discontinuation and impairment are direct evidence that the Canadian operation did not establish durable economic advantage within the case window.', factRefs: ['board-approved-exit', 'exit-charge-2014'], unknowns: ['Customer value retained outside the discontinued operation'] },
        resource: { status: 'evidenced', confidence: 'high', summary: 'The $5.105 billion pretax charge and impact on 17,600 employees make capital and workforce consequences explicit.', factRefs: ['exit-charge-2014', 'employees-at-exit'], unknowns: ['Total lifetime cash cost', 'Redeployed capability'] },
      },
      constraints: {
        people: { status: 'evidenced', confidence: 'medium', summary: 'The disclosed workforce quantifies the human scope exposed by the exit, but not pre-exit capacity utilization.', factRefs: ['employees-at-exit'], unknowns: ['Pre-exit workload', 'Skill shortages', 'Redeployment and retention'] },
        finance: { status: 'evidenced', confidence: 'high', summary: 'The recognized exit charge establishes that financial exposure had become binding at material scale.', factRefs: ['exit-charge-2014'], unknowns: ['Full cash versus non-cash decomposition'] },
        time: { status: 'evidenced', confidence: 'high', summary: 'The case moved from the 2013 mass opening to a January 2015 exit decision, leaving a short operating-learning window.', factRefs: ['planned-stores-2013', 'board-approved-exit'], unknowns: ['Internal milestone history'] },
        risk: { status: 'evidenced', confidence: 'high', summary: 'The exit charge records realized irreversible exposure after operating at national scale.', factRefs: ['stores-at-exit', 'exit-charge-2014'], unknowns: ['Precommitted exposure ceiling', 'Earlier reversible alternatives'] },
      },
    },
  ],
});
