/** Generated by scripts/schema-pin.mjs; do not edit by hand. */
export const ANSWER_SET_SCHEMA_ID = "facia.answer-set/2" as const;
export const ANSWER_SET_SCHEMA_PACKAGE_PATH =
  "@facia/core/schemas/facia-answer-set.v2.schema.json" as const;
export const ANSWER_SET_SCHEMA_SHA256 =
  "0fa2230a3db63be2684230c9e8b9da490b8705033974afd155856b28388dc45b" as const;
export const ANSWER_SET_SCHEMA_PIN = {
  schema: ANSWER_SET_SCHEMA_ID,
  packagePath: ANSWER_SET_SCHEMA_PACKAGE_PATH,
  sha256: ANSWER_SET_SCHEMA_SHA256,
} as const;
