#!/usr/bin/env node
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import * as Ajv2020Module from "ajv/dist/2020.js";
import * as standaloneCodeModule from "ajv/dist/standalone/index.js";

const packageRoot = new URL("../", import.meta.url);
const schemaUrl = new URL("schemas/facia-answer-set.v2.schema.json", packageRoot);
const pinUrl = new URL("schemas/facia-answer-set.v2.pin.json", packageRoot);
const generatedUrl = new URL("src/schema-pin.generated.ts", packageRoot);
const generatedValidatorUrl = new URL("src/answer-set-validator.generated.ts", packageRoot);
const schemaId = "facia.answer-set/2";
const packagePath = "@facia/core/schemas/facia-answer-set.v2.schema.json";

const schemaBytes = await readFile(schemaUrl);
const sha256 = createHash("sha256").update(schemaBytes).digest("hex");
const pin = { schema: schemaId, packagePath, sha256 };
const pinText = `${JSON.stringify(pin, null, 2)}\n`;
const generatedText = `/** Generated by scripts/schema-pin.mjs; do not edit by hand. */
export const ANSWER_SET_SCHEMA_ID = "${schemaId}" as const;
export const ANSWER_SET_SCHEMA_PACKAGE_PATH =
  "${packagePath}" as const;
export const ANSWER_SET_SCHEMA_SHA256 =
  "${sha256}" as const;
export const ANSWER_SET_SCHEMA_PIN = {
  schema: ANSWER_SET_SCHEMA_ID,
  packagePath: ANSWER_SET_SCHEMA_PACKAGE_PATH,
  sha256: ANSWER_SET_SCHEMA_SHA256,
} as const;
`;
const schema = JSON.parse(schemaBytes.toString("utf8"));
const Ajv2020 = Ajv2020Module.default;
const standaloneCode = standaloneCodeModule.default;
const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  code: { esm: true, source: true },
});
const validate = ajv.compile(schema);

// AJV's standalone output loads its runtime helpers with `require("...").default`
// even under `code.esm`. A bare `require` throws in any real ESM environment
// (Vite's dev SSR module runner, plain `node`), and a `createRequire` shim in
// turn breaks the edge runtime, which has no `node:module`. Rewrite each
// `require("spec").default` into a hoisted static `import`, which every ESM
// environment — dev SSR, node, bundlers, and edge — resolves natively.
function toStaticEsmImports(code) {
  const importsBySpec = new Map();
  const rewritten = code.replace(
    /require\(("|')((?:\\.|(?!\1).)*)\1\)\.default/g,
    (_match, _quote, spec) => {
      // Node's ESM resolver needs an explicit extension on deep package paths;
      // CommonJS `require` added `.js` implicitly, static `import` does not.
      // AJV's runtime helpers are always deep paths like
      // `ajv/dist/runtime/ucs2length`, so add `.js` when the final path segment
      // carries no extension. Bare package specifiers (no `/`) are left alone.
      const lastSegment = spec.slice(spec.lastIndexOf("/") + 1);
      const resolvedSpec =
        spec.includes("/") && !lastSegment.includes(".") ? `${spec}.js` : spec;
      let binding = importsBySpec.get(resolvedSpec);
      if (binding === undefined) {
        binding = `__faciaRuntime${importsBySpec.size}`;
        importsBySpec.set(resolvedSpec, binding);
      }
      // AJV's helpers are CommonJS modules that set `exports.default`. The
      // original code read `require("spec").default`. Under real Node ESM a
      // default import of such a module yields the whole `exports` object
      // (so `.default` is the helper), while esbuild/vitest interop unwraps it
      // to the helper directly (so `.default` is undefined). `.default ?? binding`
      // resolves the helper in both without a second codepath.
      return `(${binding}.default ?? ${binding})`;
    },
  );
  if (importsBySpec.size === 0) return code;
  const importLines = [...importsBySpec].map(
    ([spec, binding]) => `import ${binding} from ${JSON.stringify(spec)};`,
  );
  return `${importLines.join("\n")}\n${rewritten}`;
}

const standaloneValidator = toStaticEsmImports(standaloneCode(ajv, validate));
if (/\brequire\s*\(/.test(standaloneValidator)) {
  throw new Error(
    "Generated validator still contains a CommonJS require() after ESM rewrite; "
      + "the AJV standalone output shape changed — update toStaticEsmImports.",
  );
}
const generatedValidatorText = `/** Generated by scripts/schema-pin.mjs; do not edit by hand. */
// @ts-nocheck
${standaloneValidator}
`;

const mode = process.argv[2];
if (mode === "--write") {
  await writeFile(pinUrl, pinText);
  await writeFile(generatedUrl, generatedText);
  await writeFile(generatedValidatorUrl, generatedValidatorText);
  console.log(`Pinned ${schemaId} at sha256:${sha256}`);
} else if (mode === "--check") {
  const [actualPin, actualGenerated, actualGeneratedValidator] = await Promise.all([
    readFile(pinUrl, "utf8"),
    readFile(generatedUrl, "utf8"),
    readFile(generatedValidatorUrl, "utf8"),
  ]);
  if (
    actualPin !== pinText
    || actualGenerated !== generatedText
    || actualGeneratedValidator !== generatedValidatorText
  ) {
    console.error("AnswerSet schema pin is stale; run npm run schema:pin.");
    process.exitCode = 1;
  } else {
    console.log(`Verified ${schemaId} at sha256:${sha256}`);
  }
} else {
  console.error("Usage: node scripts/schema-pin.mjs --write|--check");
  process.exitCode = 2;
}
