#!/usr/bin/env node
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import * as Ajv2020Module from "ajv/dist/2020.js";
import * as standaloneCodeModule from "ajv/dist/standalone/index.js";

const packageRoot = new URL("../", import.meta.url);
const schemaUrl = new URL("schemas/facia-answer-set.v2.schema.json", packageRoot);
const pinUrl = new URL("schemas/facia-answer-set.v2.pin.json", packageRoot);
const generatedUrl = new URL("src/schema-pin.generated.ts", packageRoot);
const generatedValidatorUrl = new URL("src/answer-set-validator.generated.ts", packageRoot);
const schemaId = "facia.answer-set/2";
const packagePath = "@facia/core/schemas/facia-answer-set.v2.schema.json";

const schemaBytes = await readFile(schemaUrl);
const sha256 = createHash("sha256").update(schemaBytes).digest("hex");
const pin = { schema: schemaId, packagePath, sha256 };
const pinText = `${JSON.stringify(pin, null, 2)}\n`;
const generatedText = `/** Generated by scripts/schema-pin.mjs; do not edit by hand. */
export const ANSWER_SET_SCHEMA_ID = "${schemaId}" as const;
export const ANSWER_SET_SCHEMA_PACKAGE_PATH =
  "${packagePath}" as const;
export const ANSWER_SET_SCHEMA_SHA256 =
  "${sha256}" as const;
export const ANSWER_SET_SCHEMA_PIN = {
  schema: ANSWER_SET_SCHEMA_ID,
  packagePath: ANSWER_SET_SCHEMA_PACKAGE_PATH,
  sha256: ANSWER_SET_SCHEMA_SHA256,
} as const;
`;
const schema = JSON.parse(schemaBytes.toString("utf8"));
const Ajv2020 = Ajv2020Module.default;
const standaloneCode = standaloneCodeModule.default;
const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  code: { esm: true, source: true },
});
const validate = ajv.compile(schema);
// AJV's standalone output loads its runtime helpers with `require(...)` even
// under `code.esm`. That works in production bundling and in the vitest runner,
// but Vite's dev SSR module runner (used by the local API bridge) evaluates this
// ESM file without a `require` binding. Prepend a createRequire shim so the
// generated validator resolves those CJS helpers in every ESM environment.
const requireShim = `import { createRequire as __faciaCreateRequire } from "node:module";
const require = __faciaCreateRequire(import.meta.url);`;
const generatedValidatorText = `/** Generated by scripts/schema-pin.mjs; do not edit by hand. */
// @ts-nocheck
${requireShim}
${standaloneCode(ajv, validate)}
`;

const mode = process.argv[2];
if (mode === "--write") {
  await writeFile(pinUrl, pinText);
  await writeFile(generatedUrl, generatedText);
  await writeFile(generatedValidatorUrl, generatedValidatorText);
  console.log(`Pinned ${schemaId} at sha256:${sha256}`);
} else if (mode === "--check") {
  const [actualPin, actualGenerated, actualGeneratedValidator] = await Promise.all([
    readFile(pinUrl, "utf8"),
    readFile(generatedUrl, "utf8"),
    readFile(generatedValidatorUrl, "utf8"),
  ]);
  if (
    actualPin !== pinText
    || actualGenerated !== generatedText
    || actualGeneratedValidator !== generatedValidatorText
  ) {
    console.error("AnswerSet schema pin is stale; run npm run schema:pin.");
    process.exitCode = 1;
  } else {
    console.log(`Verified ${schemaId} at sha256:${sha256}`);
  }
} else {
  console.error("Usage: node scripts/schema-pin.mjs --write|--check");
  process.exitCode = 2;
}
