#!/usr/bin/env node
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";

const packageRoot = new URL("../", import.meta.url);
const schemaUrl = new URL("schemas/facia-answer-set.v2.schema.json", packageRoot);
const pinUrl = new URL("schemas/facia-answer-set.v2.pin.json", packageRoot);
const generatedUrl = new URL("src/schema-pin.generated.ts", packageRoot);
const schemaId = "facia.answer-set/2";
const packagePath = "@facia/core/schemas/facia-answer-set.v2.schema.json";

const schemaBytes = await readFile(schemaUrl);
const sha256 = createHash("sha256").update(schemaBytes).digest("hex");
const pin = { schema: schemaId, packagePath, sha256 };
const pinText = `${JSON.stringify(pin, null, 2)}\n`;
const generatedText = `/** Generated by scripts/schema-pin.mjs; do not edit by hand. */
export const ANSWER_SET_SCHEMA_ID = "${schemaId}" as const;
export const ANSWER_SET_SCHEMA_PACKAGE_PATH =
  "${packagePath}" as const;
export const ANSWER_SET_SCHEMA_SHA256 =
  "${sha256}" as const;
export const ANSWER_SET_SCHEMA_PIN = {
  schema: ANSWER_SET_SCHEMA_ID,
  packagePath: ANSWER_SET_SCHEMA_PACKAGE_PATH,
  sha256: ANSWER_SET_SCHEMA_SHA256,
} as const;
`;

const mode = process.argv[2];
if (mode === "--write") {
  await writeFile(pinUrl, pinText);
  await writeFile(generatedUrl, generatedText);
  console.log(`Pinned ${schemaId} at sha256:${sha256}`);
} else if (mode === "--check") {
  const [actualPin, actualGenerated] = await Promise.all([
    readFile(pinUrl, "utf8"),
    readFile(generatedUrl, "utf8"),
  ]);
  if (actualPin !== pinText || actualGenerated !== generatedText) {
    console.error("AnswerSet schema pin is stale; run npm run schema:pin.");
    process.exitCode = 1;
  } else {
    console.log(`Verified ${schemaId} at sha256:${sha256}`);
  }
} else {
  console.error("Usage: node scripts/schema-pin.mjs --write|--check");
  process.exitCode = 2;
}
